from __future__ import annotations

import logging

import pandas as pd

from config import settings


LOGGER = logging.getLogger(__name__)


SAMPLE_OFFERS = [
    {
        "offer_id": "jasper-ai",
        "brand_name": "Jasper AI",
        "website": "https://www.jasper.ai",
        "affiliate_url": "https://www.jasper.ai/partners",
        "niche": "AI Writing",
        "commission_type": "recurring",
        "commission_rate": 30,
        "flat_commission": 0,
        "cookie_days": 45,
        "recurring": True,
        "traffic_policy": "paid search allowed, no trademark bidding, no direct linking",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 86,
        "buyer_intent": 88,
        "notes": "Strong B2B creator demand.",
    },
    {
        "offer_id": "surfer-seo",
        "brand_name": "Surfer SEO",
        "website": "https://surferseo.com",
        "affiliate_url": "https://surferseo.com/affiliate-program/",
        "niche": "AI SEO",
        "commission_type": "recurring",
        "commission_rate": 25,
        "flat_commission": 0,
        "cookie_days": 60,
        "recurring": True,
        "traffic_policy": "paid search allowed, no trademark bidding",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 84,
        "buyer_intent": 86,
        "notes": "Good comparison/review intent.",
    },
    {
        "offer_id": "synthesia",
        "brand_name": "Synthesia",
        "website": "https://www.synthesia.io",
        "affiliate_url": "https://www.synthesia.io/affiliate-program",
        "niche": "AI Video",
        "commission_type": "percentage",
        "commission_rate": 20,
        "flat_commission": 0,
        "cookie_days": 30,
        "recurring": False,
        "traffic_policy": "paid search allowed, brand bidding restricted",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 88,
        "buyer_intent": 82,
        "notes": "Enterprise and creator use cases.",
    },
    {
        "offer_id": "elevenlabs",
        "brand_name": "ElevenLabs",
        "website": "https://elevenlabs.io",
        "affiliate_url": "https://elevenlabs.io/affiliate",
        "niche": "AI Voice",
        "commission_type": "recurring",
        "commission_rate": 22,
        "flat_commission": 0,
        "cookie_days": 30,
        "recurring": True,
        "traffic_policy": "review content allowed, no misleading voice claims",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 83,
        "buyer_intent": 78,
        "notes": "High interest but policy needs careful copy.",
    },
    {
        "offer_id": "notion",
        "brand_name": "Notion",
        "website": "https://www.notion.com",
        "affiliate_url": "https://www.notion.com/affiliates",
        "niche": "Productivity",
        "commission_type": "flat",
        "commission_rate": 0,
        "flat_commission": 50,
        "cookie_days": 30,
        "recurring": False,
        "traffic_policy": "paid search allowed, no trademark bidding",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 92,
        "buyer_intent": 76,
        "notes": "Broad market, higher competition.",
    },
    {
        "offer_id": "make",
        "brand_name": "Make",
        "website": "https://www.make.com",
        "affiliate_url": "https://www.make.com/en/affiliates",
        "niche": "Automation",
        "commission_type": "recurring",
        "commission_rate": 20,
        "flat_commission": 0,
        "cookie_days": 90,
        "recurring": True,
        "traffic_policy": "content and search allowed, no trademark bidding",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 85,
        "buyer_intent": 84,
        "notes": "Strong workflow automation angle.",
    },
    {
        "offer_id": "hubspot",
        "brand_name": "HubSpot",
        "website": "https://www.hubspot.com",
        "affiliate_url": "https://www.hubspot.com/partners/affiliates",
        "niche": "CRM",
        "commission_type": "flat",
        "commission_rate": 0,
        "flat_commission": 1000,
        "cookie_days": 90,
        "recurring": False,
        "traffic_policy": "no trademark bidding, no coupon abuse, paid search restricted",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 94,
        "buyer_intent": 90,
        "notes": "High payout, high competition.",
    },
    {
        "offer_id": "activecampaign",
        "brand_name": "ActiveCampaign",
        "website": "https://www.activecampaign.com",
        "affiliate_url": "https://www.activecampaign.com/partner/affiliate",
        "niche": "Email Marketing",
        "commission_type": "recurring",
        "commission_rate": 30,
        "flat_commission": 0,
        "cookie_days": 90,
        "recurring": True,
        "traffic_policy": "paid search allowed with restrictions, no trademark bidding",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 87,
        "buyer_intent": 85,
        "notes": "Good alternative/comparison keywords.",
    },
    {
        "offer_id": "canva",
        "brand_name": "Canva",
        "website": "https://www.canva.com",
        "affiliate_url": "https://www.canva.com/affiliates/",
        "niche": "AI Design",
        "commission_type": "flat",
        "commission_rate": 0,
        "flat_commission": 36,
        "cookie_days": 30,
        "recurring": False,
        "traffic_policy": "no trademark bidding, coupon restrictions",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 93,
        "buyer_intent": 73,
        "notes": "Huge demand, competitive SERP.",
    },
    {
        "offer_id": "reclaim-ai",
        "brand_name": "Reclaim AI",
        "website": "https://reclaim.ai",
        "affiliate_url": "https://reclaim.ai/affiliate",
        "niche": "AI Meeting",
        "commission_type": "recurring",
        "commission_rate": 25,
        "flat_commission": 0,
        "cookie_days": 60,
        "recurring": True,
        "traffic_policy": "paid search allowed, no misleading productivity claims",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 78,
        "buyer_intent": 80,
        "notes": "Rising calendar automation niche.",
    },
    {
        "offer_id": "gamma",
        "brand_name": "Gamma",
        "website": "https://gamma.app",
        "affiliate_url": "",
        "niche": "AI Productivity",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 76,
        "buyer_intent": 72,
        "notes": "Presentation and document creation tool. Affiliate terms need manual verification.",
    },
    {
        "offer_id": "webflow-ai",
        "brand_name": "Webflow AI",
        "website": "https://webflow.com/ai",
        "affiliate_url": "",
        "niche": "Website Builder",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 88,
        "buyer_intent": 80,
        "notes": "Website builder and AI-assisted site workflow angle.",
    },
    {
        "offer_id": "adcreative-ai",
        "brand_name": "AdCreative AI",
        "website": "https://www.adcreative.ai",
        "affiliate_url": "",
        "niche": "Marketing",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 74,
        "buyer_intent": 78,
        "notes": "Ad creative generation tool for marketers. Claims need careful wording.",
    },
    {
        "offer_id": "pipedrive-crm",
        "brand_name": "Pipedrive CRM",
        "website": "https://www.pipedrive.com",
        "affiliate_url": "",
        "niche": "CRM",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 86,
        "buyer_intent": 84,
        "notes": "Sales CRM with strong comparison and alternative search intent.",
    },
    {
        "offer_id": "pipedrive",
        "brand_name": "Pipedrive",
        "website": "https://www.pipedrive.com",
        "affiliate_url": "",
        "niche": "CRM",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 86,
        "buyer_intent": 84,
        "notes": "Sales CRM with strong comparison and alternative search intent.",
    },
    {
        "offer_id": "notion-ai",
        "brand_name": "Notion AI",
        "website": "https://www.notion.com/product/ai",
        "affiliate_url": "",
        "niche": "AI Productivity",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 90,
        "buyer_intent": 78,
        "notes": "Workspace AI assistant angle for productivity and content workflows.",
    },
    {
        "offer_id": "jasper",
        "brand_name": "Jasper",
        "website": "https://www.jasper.ai",
        "affiliate_url": "https://www.jasper.ai/partners",
        "niche": "AI Writing",
        "commission_type": "recurring",
        "commission_rate": 30,
        "flat_commission": 0,
        "cookie_days": 45,
        "recurring": True,
        "traffic_policy": "paid search allowed, no trademark bidding, no direct linking",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 86,
        "buyer_intent": 88,
        "notes": "AI writing and marketing content tool with strong buyer intent.",
    },
    {
        "offer_id": "copy-ai",
        "brand_name": "Copy.ai",
        "website": "https://www.copy.ai",
        "affiliate_url": "",
        "niche": "AI Writing",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 82,
        "buyer_intent": 82,
        "notes": "AI writing and go-to-market workflow tool.",
    },
    {
        "offer_id": "descript",
        "brand_name": "Descript",
        "website": "https://www.descript.com",
        "affiliate_url": "",
        "niche": "AI Video",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 84,
        "buyer_intent": 80,
        "notes": "Video and podcast editing workflow with AI features.",
    },
    {
        "offer_id": "runway",
        "brand_name": "Runway",
        "website": "https://runwayml.com",
        "affiliate_url": "",
        "niche": "AI Video",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 86,
        "buyer_intent": 79,
        "notes": "AI video generation and creative editing workflow.",
    },
    {
        "offer_id": "zapier",
        "brand_name": "Zapier",
        "website": "https://zapier.com",
        "affiliate_url": "",
        "niche": "Automation",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 90,
        "buyer_intent": 86,
        "notes": "Automation platform with strong comparison intent against Make.",
    },
    {
        "offer_id": "framer",
        "brand_name": "Framer",
        "website": "https://www.framer.com",
        "affiliate_url": "",
        "niche": "Website Builder",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 84,
        "buyer_intent": 81,
        "notes": "Website builder for modern marketing sites and design-led teams.",
    },
    {
        "offer_id": "webflow",
        "brand_name": "Webflow",
        "website": "https://webflow.com",
        "affiliate_url": "",
        "niche": "Website Builder",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 89,
        "buyer_intent": 83,
        "notes": "Professional website builder and CMS workflow.",
    },
    {
        "offer_id": "durable",
        "brand_name": "Durable",
        "website": "https://durable.co",
        "affiliate_url": "",
        "niche": "Website Builder",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 76,
        "buyer_intent": 74,
        "notes": "AI website builder for small business website drafts.",
    },
    {
        "offer_id": "cursor",
        "brand_name": "Cursor",
        "website": "https://cursor.com",
        "affiliate_url": "",
        "niche": "AI Coding",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 84,
        "buyer_intent": 86,
        "notes": "AI coding editor with strong developer search demand.",
    },
    {
        "offer_id": "github-copilot",
        "brand_name": "GitHub Copilot",
        "website": "https://github.com/features/copilot",
        "affiliate_url": "",
        "niche": "AI Coding",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 94,
        "buyer_intent": 88,
        "notes": "AI coding assistant with very high brand awareness.",
    },
    {
        "offer_id": "semrush",
        "brand_name": "Semrush",
        "website": "https://www.semrush.com",
        "affiliate_url": "",
        "niche": "AI SEO",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - affiliate approval and paid search policy not verified",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "vendor_trust": 92,
        "buyer_intent": 90,
        "notes": "SEO suite with high-intent comparison and alternatives search.",
    },
]


def ensure_sample_offers() -> None:
    if settings.offers_file.exists():
        try:
            current = pd.read_csv(settings.offers_file)
            seed = pd.DataFrame(SAMPLE_OFFERS)
            if "offer_id" in current.columns:
                missing = seed[~seed["offer_id"].isin(current["offer_id"].astype(str))]
                if not missing.empty:
                    pd.concat([current, missing], ignore_index=True, sort=False).to_csv(settings.offers_file, index=False)
        except Exception:
            LOGGER.exception("Could not merge sample offers")
        return
    LOGGER.info("Creating sample offers: %s", settings.offers_file)
    pd.DataFrame(SAMPLE_OFFERS).to_csv(settings.offers_file, index=False)


def load_offers() -> pd.DataFrame:
    ensure_sample_offers()
    try:
        offers = pd.read_csv(settings.offers_file)
    except Exception:
        LOGGER.exception("Could not load offers file")
        offers = pd.DataFrame()
    user_offers = load_user_offers()
    frames = [df for df in [offers, user_offers] if not df.empty]
    if not frames:
        return pd.DataFrame()
    merged = pd.concat(frames, ignore_index=True, sort=False).fillna("")
    if "offer_id" in merged.columns:
        merged = merged.drop_duplicates(subset=["offer_id"], keep="last")
    return normalize_offer_columns(merged)


def load_user_offers() -> pd.DataFrame:
    if not settings.user_offers_file.exists():
        settings.user_offers_file.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(columns=[
            "offer_id",
            "brand_name",
            "website",
            "affiliate_program_url",
            "affiliate_url",
            "terms_url",
            "network",
            "niche",
            "commission_type",
            "commission_rate",
            "flat_commission",
            "cookie_days",
            "recurring",
            "traffic_policy",
            "brand_bidding_allowed",
            "direct_linking_allowed",
            "country_allowed",
            "data_confidence",
            "data_source_note",
            "last_checked",
            "manual_note",
        ]).to_csv(settings.user_offers_file, index=False)
        return pd.DataFrame()
    try:
        return pd.read_csv(settings.user_offers_file)
    except Exception:
        LOGGER.exception("Could not load user offers file")
        return pd.DataFrame()


def normalize_offer_columns(df: pd.DataFrame) -> pd.DataFrame:
    defaults = {
        "affiliate_url": "",
        "affiliate_program_url": "",
        "terms_url": "",
        "network": "Other",
        "niche": "UNKNOWN",
        "commission_type": "UNKNOWN",
        "commission_rate": 0,
        "flat_commission": 0,
        "cookie_days": 0,
        "recurring": False,
        "traffic_policy": "NEED_REVIEW - Chưa xác minh chính sách affiliate terms",
        "direct_linking_allowed": False,
        "brand_bidding_allowed": False,
        "country_allowed": "UNKNOWN",
        "data_confidence": "LOW",
        "data_source_note": "Dữ liệu chưa xác minh.",
        "last_checked": "",
        "manual_note": "",
        "vendor_trust": 45,
        "buyer_intent": 55,
        "notes": "",
    }
    for column, default in defaults.items():
        if column not in df.columns:
            df[column] = default
    return df.fillna(defaults)
