from __future__ import annotations

import re


MOJIBAKE_REPLACEMENTS = {
    "PhÃ¹ há»£p vá»›i": "Phù hợp với",
    "KhÃ´ng phÃ¹ há»£p náº¿u": "Không phù hợp nếu",
    "Khi nÃ o nÃªn dÃ¹ng?": "Khi nào nên dùng?",
    "Khi nÃ o KHÃ”NG nÃªn dÃ¹ng?": "Khi nào KHÔNG nên dùng?",
    "Workflow phÃ¹ há»£p": "Workflow phù hợp",
    "Äá»‘i tÆ°á»£ng phÃ¹ há»£p nháº¥t": "Đối tượng phù hợp nhất",
    "CÃ´ng cá»¥ nÃ y giáº£i quyáº¿t viá»‡c gÃ¬?": "Công cụ này giải quyết việc gì?",
    "Ai nÃªn cÃ¢n nháº¯c?": "Ai nên cân nhắc?",
    "TÃ­nh nÄƒng Ä‘Ã¡ng chÃº Ã½": "Tính năng đáng chú ý",
    "Äiá»ƒm máº¡nh ná»•i báº­t": "Điểm mạnh nổi bật",
    "Äiá»ƒm gÃ¢y khÃ³ chá»‹u": "Điểm gây khó chịu",
    "Æ¯u Ä‘iá»ƒm": "Ưu điểm",
    "NhÆ°á»£c Ä‘iá»ƒm / háº¡n cháº¿": "Nhược điểm / hạn chế",
    "Báº£ng Æ°u Ä‘iá»ƒm / háº¡n cháº¿": "Bảng ưu điểm / hạn chế",
    "Giáº£i thÃ­ch Ä‘iá»ƒm sá»‘": "Giải thích điểm số",
    "Ghi chÃº pricing": "Ghi chú giá",
    "HÃ£y xÃ¡c minh giÃ¡ hiá»‡n táº¡i trÃªn website chÃ­nh thá»©c.": "Hãy xác minh giá hiện tại trên website chính thức.",
    "Pricing, trial, giá»›i háº¡n plan vÃ  Ä‘iá»u khoáº£n há»§y cÃ³ thá»ƒ thay Ä‘á»•i theo thá»i gian.": "Giá, bản dùng thử, giới hạn gói và điều khoản hủy có thể thay đổi theo thời gian.",
    "TÃ³m táº¯t pricing": "Tóm tắt giá",
    "Review nghiÃªn cá»©u vá»": "Review nghiên cứu về",
    "Ä‘iá»ƒm máº¡nh": "điểm mạnh",
    "háº¡n cháº¿": "hạn chế",
    "vÃ  affiliate disclosure": "và tiết lộ liên kết",
    "á»Ÿ website chÃ­nh thá»©c": "ở website chính thức",
    "âœ“ Pros": "Ưu điểm",
    "âš  Cons": "Hạn chế",
}


UI_REPLACEMENTS = {
    "AI Tool Review Center": "Trung tâm đánh giá công cụ AI",
    "AI Tool": "Công cụ AI",
    "Review": "Đánh giá",
    "Independent-style reviews": "Đánh giá độc lập theo hướng nghiên cứu",
    "Some links may be affiliate links. We may earn a commission at no extra cost to you.": "Một số liên kết có thể là liên kết tiếp thị liên kết. Chúng tôi có thể nhận hoa hồng mà không phát sinh thêm chi phí cho bạn.",
    "Some links may be affiliate links. We may earn a commission at no extra cost to you": "Một số liên kết có thể là liên kết tiếp thị liên kết. Chúng tôi có thể nhận hoa hồng mà không phát sinh thêm chi phí cho bạn",
    "This review is for research purposes only.": "Bài đánh giá này chỉ phục vụ mục đích nghiên cứu.",
    "We may earn commission if you purchase through our links. This does not change your price.": "Chúng tôi có thể nhận hoa hồng nếu bạn mua qua liên kết của chúng tôi. Điều này không làm thay đổi giá bạn trả.",
    "Reviews are for research purposes only.": "Các bài đánh giá chỉ nhằm mục đích nghiên cứu.",
    "Home": "Trang chủ",
    "Reviews": "Đánh giá",
    "Comparisons": "So sánh",
    "Pricing": "Giá",
    "Categories": "Danh mục",
    "Hubs": "Trung tâm",
    "Contact": "Liên hệ",
    "Privacy Policy": "Chính sách bảo mật",
    "Terms": "Điều khoản",
    "Disclosure": "Tiết lộ liên kết",
    "Affiliate Disclosure": "Tiết lộ liên kết",
    "About": "Giới thiệu",
    "About Author": "Giới thiệu tác giả",
    "Editorial Policy": "Chính sách biên tập",
    "Testing Methodology": "Phương pháp thử nghiệm",
    "Contents": "Nội dung",
    "Overview": "Tổng quan",
    "Features": "Tính năng",
    "Pros and Cons": "Ưu điểm và hạn chế",
    "Who Should Use It": "Ai nên dùng?",
    "Alternatives": "Lựa chọn thay thế",
    "FAQ": "Câu hỏi thường gặp",
    "Final Verdict": "Kết luận cuối",
    "Final verdict": "Kết luận cuối",
    "Final recommendation": "Khuyến nghị cuối",
    "Short answer:": "Tóm tắt nhanh:",
    "Visit Official Website": "Truy cập website chính thức",
    "Verify Current Pricing": "Kiểm tra giá hiện tại",
    "Check current pricing": "Kiểm tra giá hiện tại",
    "Affiliate link pending approval.": "Liên kết tiếp thị đang chờ phê duyệt.",
    "Rating Summary": "Tóm tắt điểm đánh giá",
    "Featured image placeholder": "Ảnh minh họa",
    "research overview": "tổng quan nghiên cứu",
    "Ease of use": "Dễ sử dụng",
    "Features": "Tính năng",
    "Best for": "Phù hợp nhất",
    "teams comparing SaaS tools": "nhóm đang so sánh công cụ SaaS",
    "Last updated:": "Cập nhật lần cuối:",
    "Share:": "Chia sẻ:",
    "Affiliate disclosure:": "Tiết lộ liên kết:",
    "Affiliate disclosure": "Tiết lộ liên kết",
    "Affiliate link field": "Trạng thái liên kết tiếp thị",
    "Status:": "Trạng thái:",
    "CTA URL used now:": "URL CTA đang dùng:",
    "Replace this with an approved affiliate link only after the affiliate program approves your account. Do not use fake affiliate links.": "Chỉ thay bằng link affiliate thật sau khi chương trình tiếp thị liên kết phê duyệt tài khoản. Không dùng link affiliate giả.",
    "Comparison table": "Bảng so sánh",
    "Feature comparison table": "Bảng so sánh tính năng",
    "Pricing comparison": "So sánh giá",
    "Pricing summary": "Tóm tắt giá",
    "Pricing note": "Ghi chú giá",
    "Pricing Guides": "Hướng dẫn giá",
    "Pricing Guide": "Hướng dẫn giá",
    "Pricing research": "Nghiên cứu giá",
    "Tool": "Công cụ",
    "Pricing type": "Kiểu giá",
    "Pros": "Ưu điểm",
    "Cons": "Hạn chế",
    "Best alternatives": "Lựa chọn thay thế tốt",
    "Good alternatives depend on your budget, workflow and required integrations. Compare at least two or three tools before buying.": "Lựa chọn thay thế phù hợp phụ thuộc vào ngân sách, workflow và tích hợp bạn cần. Nên so sánh ít nhất hai hoặc ba công cụ trước khi mua.",
    "How we tested": "Cách chúng tôi đánh giá",
    "Internal links for deeper research": "Liên kết nội bộ để nghiên cứu sâu hơn",
    "Related comparisons": "So sánh liên quan",
    "Alternatives and similar tools": "Lựa chọn thay thế và công cụ tương tự",
    "Related research": "Nội dung liên quan",
    "Related reviews": "Đánh giá liên quan",
    "Popular reviews": "Đánh giá phổ biến",
    "Popular comparisons": "So sánh phổ biến",
    "Pricing pages": "Trang giá",
    "Pricing research": "Nghiên cứu giá",
    "Top lists": "Danh sách nổi bật",
    "Top categories": "Danh mục nổi bật",
    "Best category pages": "Trang danh mục phù hợp",
    "Best category page": "Trang danh mục phù hợp",
    "Alternatives and related tools": "Lựa chọn thay thế và công cụ liên quan",
    "Reviews in this category": "Đánh giá trong danh mục này",
    "Comparison pages": "Trang so sánh",
    "Related pricing pages": "Trang giá liên quan",
    "Related hubs": "Trung tâm liên quan",
    "Priority pages": "Trang ưu tiên",
    "Author": "Tác giả",
    "Independent AI & SaaS Researcher": "Người nghiên cứu AI & SaaS độc lập",
    "Researching AI tools, SaaS software, automation systems, and productivity workflows.": "Nghiên cứu công cụ AI, phần mềm SaaS, hệ thống tự động hóa và workflow năng suất.",
    "Research methodology": "Phương pháp nghiên cứu",
    "Tested feature review": "Đánh giá tính năng đã kiểm tra",
    "Public pricing review": "Kiểm tra thông tin giá công khai",
    "UI evaluation": "Đánh giá giao diện",
    "Workflow comparison": "So sánh workflow",
    "User feedback research": "Nghiên cứu phản hồi người dùng",
    "Get new AI tool reviews and comparisons.": "Nhận cập nhật review và so sánh công cụ AI mới.",
    "Join the research list for new AI/SaaS review updates. No backend is connected yet; this placeholder is ready for a future email provider.": "Theo dõi các cập nhật review AI/SaaS mới. Hiện chưa kết nối backend email; phần này sẵn sàng để tích hợp nhà cung cấp email sau.",
    "Notify me": "Thông báo cho tôi",
    "Compare now": "So sánh ngay",
    "See alternatives": "Xem lựa chọn thay thế",
    "Compare more tools": "So sánh thêm công cụ",
    "Browse reviews": "Xem danh sách đánh giá",
    "Read review": "Đọc đánh giá",
    "Read related reviews": "Đọc đánh giá liên quan",
    "Compare tools": "So sánh công cụ",
    "Browse comparisons": "Xem các bài so sánh",
    "All comparisons": "Tất cả bài so sánh",
    "All reviews": "Tất cả bài đánh giá",
    "Check pricing guides": "Xem hướng dẫn giá",
    "Explore categories": "Khám phá danh mục",
    "Related category": "Danh mục liên quan",
    "Next step": "Bước tiếp theo",
    "What to verify": "Cần xác minh",
    "Risk signal": "Tín hiệu rủi ro",
    "Area": "Tiêu chí",
    "Best fit": "Phù hợp nhất",
    "Context awareness": "Hiểu ngữ cảnh",
    "Autocomplete feel": "Cảm giác autocomplete",
    "Multi-file editing": "Chỉnh sửa nhiều file",
    "Pricing risk": "Rủi ro giá",
    "Tool posture": "Định vị công cụ",
    "Enterprise fit": "Phù hợp doanh nghiệp",
    "Editor workflow": "Workflow trong editor",
    "Autocomplete speed": "Tốc độ autocomplete",
    "Weaknesses": "Điểm yếu",
    "Strengths": "Điểm mạnh",
    "Quick comparison": "So sánh nhanh",
    "Pros and cons": "Ưu điểm và hạn chế",
    "Best use case": "Use case phù hợp nhất",
    "Who should avoid": "Ai không nên dùng?",
}


PHRASE_REPLACEMENTS = {
    "Clear category fit for comparison content.": "Phù hợp rõ với nội dung so sánh trong cùng danh mục.",
    "High buyer intent signal.": "Có tín hiệu ý định mua cao.",
    "Positive estimated ROI signal, pending real campaign data.": "Có tín hiệu ROI dự kiến tích cực, nhưng vẫn cần dữ liệu chiến dịch thật.",
    "Pricing and terms must be checked on the official website.": "Cần kiểm tra giá và điều khoản trên website chính thức.",
    "Direct affiliate linking should be avoided unless terms allow it.": "Không nên dùng link affiliate trực tiếp trừ khi điều khoản cho phép.",
    "Trademark bidding should be avoided.": "Không nên bid từ khóa thương hiệu.",
    "Current data confidence is low and needs manual verification.": "Độ tin cậy dữ liệu hiện còn thấp và cần kiểm tra thủ công.",
    "Core workflow support for AI Coding.": "Hỗ trợ workflow chính cho AI Coding.",
    "Useful for review, comparison and product research workflows.": "Hữu ích cho workflow đánh giá, so sánh và nghiên cứu sản phẩm.",
    "Requires official pricing and policy verification before paid promotion.": "Cần xác minh giá và chính sách chính thức trước khi quảng bá trả phí.",
    "Pricing can change. Use this review as a research starting point and confirm the latest plan limits, trial terms, cancellation terms, and commercial usage rules on the official website.": "Giá có thể thay đổi. Hãy xem bài review này như điểm bắt đầu nghiên cứu và xác minh giới hạn gói, điều khoản dùng thử, điều khoản hủy và quyền sử dụng thương mại mới nhất trên website chính thức.",
    "Reviewed the public product positioning and feature set.": "Đã xem xét định vị sản phẩm công khai và bộ tính năng.",
    "Compared the tool against category alternatives.": "Đã so sánh công cụ với các lựa chọn cùng danh mục.",
    "Checked pricing and policy areas that require manual verification.": "Đã kiểm tra các phần giá và chính sách cần xác minh thủ công.",
    "Evaluated workflow fit for realistic business use cases.": "Đã đánh giá mức phù hợp workflow cho các use case kinh doanh thực tế.",
    "May fit different workflows": "Có thể phù hợp với workflow khác",
    "Requires separate verification": "Cần xác minh riêng",
    "Teams comparing": "Nhóm đang so sánh",
    "Budget-sensitive buyers": "Người mua nhạy cảm với ngân sách",
    "May offer simpler entry plan": "Có thể có gói khởi đầu đơn giản hơn",
    "Feature depth may differ": "Độ sâu tính năng có thể khác",
    "Check official pricing.": "Kiểm tra giá trên website chính thức.",
    "Check official pricing": "Kiểm tra giá chính thức",
    "Check official pricing for both tools before buying, writing affiliate content, or sending paid traffic.": "Hãy kiểm tra giá chính thức của cả hai công cụ trước khi mua, viết nội dung affiliate hoặc chạy traffic trả phí.",
    "Also compare related reviews and broader category pages before deciding.": "Nên so sánh thêm các bài review liên quan và trang danh mục rộng hơn trước khi quyết định.",
}


PAGE_TEXT_REPLACEMENTS = {
    "Introduction": "Giới thiệu",
    "Cursor vs Windsurf: Which AI Coding Editor Fits Real Development Work?": "Cursor vs Windsurf: trình soạn thảo AI nào phù hợp với workflow lập trình thực tế?",
    "Cursor vs Windsurf: Which AI Coding Editor Should You Test First?": "Cursor vs Windsurf: nên thử trình soạn thảo mã AI nào trước?",
    "Copilot vs Cursor: Enterprise Assistant or AI-First Coding Editor?": "Copilot vs Cursor: trợ lý doanh nghiệp hay trình soạn thảo AI-first?",
    "Copilot vs Cursor: Which AI Coding Workflow Makes More Sense?": "Copilot vs Cursor: workflow lập trình AI nào hợp lý hơn?",
    "Cursor is the better first test if you want a controlled AI-first coding editor; Windsurf is the more interesting test if you want to explore agent-style coding workflows.": "Cursor là lựa chọn nên thử trước nếu bạn muốn một trình soạn thảo AI-first dễ kiểm soát; Windsurf đáng thử nếu bạn muốn khám phá workflow lập trình kiểu agent.",
    "The real question is not which product has the better demo. The real question is which tool helps you understand, edit, test, and review code with less friction inside your own repository.": "Câu hỏi thực sự không phải sản phẩm nào có demo đẹp hơn. Câu hỏi thực tế là công cụ nào giúp bạn hiểu, chỉnh sửa, kiểm thử và review code ít ma sát hơn ngay trong repository của mình.",
    "This comparison focuses on context awareness, autocomplete behavior, terminal integration, multi-file editing, pricing risk, onboarding difficulty, and when a developer should avoid either option.": "Bài so sánh này tập trung vào khả năng hiểu ngữ cảnh, autocomplete, tích hợp terminal, chỉnh sửa nhiều file, rủi ro giá, độ khó khi làm quen và khi nào lập trình viên nên tránh từng lựa chọn.",
    "For affiliate and SEO content, this is a high-intent page because readers searching Cursor vs Windsurf are usually close to testing one of the tools. The recommendation should be specific, cautious, and useful rather than aggressively promotional.": "Với nội dung SEO/affiliate, đây là trang có intent cao vì người tìm Cursor vs Windsurf thường đã gần đến bước thử một trong hai công cụ. Khuyến nghị cần cụ thể, thận trọng và hữu ích thay vì quảng bá quá đà.",
    "Where the comparison actually matters": "Điểm so sánh thực sự quan trọng",
    "Cursor and Windsurf are not just autocomplete tools. They are competing ideas about how much of the coding workflow should live inside an AI-assisted editor. The important questions are practical: does the tool understand the codebase, can it safely edit multiple files, does it recover when the first plan is wrong, and how much manual cleanup remains after the assistant finishes.": "Cursor và Windsurf không chỉ là công cụ autocomplete. Chúng đại diện cho hai cách nghĩ khác nhau về việc bao nhiêu phần của workflow lập trình nên nằm trong một editor có AI hỗ trợ. Câu hỏi quan trọng rất thực tế: công cụ có hiểu codebase không, có chỉnh sửa nhiều file an toàn không, có phục hồi được khi kế hoạch đầu sai không, và sau khi AI hoàn tất thì còn phải dọn thủ công bao nhiêu.",
    "Cursor feels strongest when a developer wants tight control and fast movement inside a familiar AI-first editor. Windsurf is interesting when the workflow leans more toward agentic steps and guided changes. I would not judge either tool from a blank-file demo; use an existing repository with tests, config files, and messy naming conventions.": "Cursor mạnh nhất khi lập trình viên muốn kiểm soát chặt và di chuyển nhanh trong một editor AI-first quen tay. Windsurf thú vị hơn khi workflow nghiêng về các bước kiểu agent và thay đổi có hướng dẫn. Không nên đánh giá hai công cụ bằng demo file trống; hãy dùng một repository thật có test, file cấu hình và quy ước đặt tên lộn xộn.",
    "Recommendation after a one-week pilot": "Khuyến nghị sau một tuần thử nghiệm",
    "If a one-week pilot shows Cursor reducing time spent on codebase exploration and small refactors, I would keep Cursor as the main editor for individual developer workflows. It is most persuasive when the developer can point to specific tasks that became easier, not just a general feeling that AI is faster.": "Nếu một tuần thử nghiệm cho thấy Cursor giảm thời gian đọc codebase và refactor nhỏ, tôi sẽ giữ Cursor làm editor chính cho workflow cá nhân. Tín hiệu thuyết phục nhất là lập trình viên chỉ ra được task cụ thể đã dễ hơn, không chỉ cảm giác chung chung rằng AI nhanh hơn.",
    "If Windsurf handles multi-step changes with fewer manual resets, it becomes a stronger candidate for developers who want a more agentic coding loop. The key metric is not how much code it writes. The key metric is how much of that code survives review after tests and human inspection.": "Nếu Windsurf xử lý các thay đổi nhiều bước với ít lần phải reset thủ công hơn, nó trở thành ứng viên mạnh cho người muốn vòng lặp lập trình kiểu agent. Thước đo chính không phải nó viết bao nhiêu code, mà là bao nhiêu phần code đó qua được review sau khi chạy test và kiểm tra thủ công.",
    "If neither tool clearly improves the workflow, stay with the existing editor and test GitHub Copilot or another assistant layer. The best outcome of a pilot is not always buying a tool; sometimes it is learning that the team needs better tests, clearer tickets, or smaller pull requests before AI coding tools can help.": "Nếu không công cụ nào cải thiện workflow rõ ràng, hãy giữ editor hiện tại và thử GitHub Copilot hoặc một lớp trợ lý nhẹ hơn. Kết quả tốt nhất của một đợt thử nghiệm không phải lúc nào cũng là mua tool; đôi khi là nhận ra team cần test tốt hơn, ticket rõ hơn hoặc pull request nhỏ hơn trước khi AI coding tool thật sự giúp được.",
    "Search intent and conversion notes": "Ý định tìm kiếm và ghi chú chuyển đổi",
    "A reader searching Cursor vs Windsurf is usually not at the top of the funnel. They already know both names and are trying to understand which one deserves a trial. That makes the page useful for affiliate conversion, but only if the recommendation feels earned. The content should help the reader choose a test path, not pressure them into clicking both official sites.": "Người tìm Cursor vs Windsurf thường không còn ở đầu phễu. Họ đã biết cả hai tên và đang muốn hiểu công cụ nào đáng thử. Điều đó khiến trang này có giá trị cho affiliate conversion, nhưng chỉ khi khuyến nghị có lý do rõ ràng. Nội dung nên giúp người đọc chọn hướng test, không ép họ bấm cả hai website chính thức.",
    "For Cursor, the conversion angle is control and immediate productivity inside an AI-first editor. For Windsurf, the angle is exploring whether agent-style coding can reduce manual coordination during larger tasks. These are different promises, so the CTA copy should not treat them as interchangeable products.": "Với Cursor, góc chuyển đổi là khả năng kiểm soát và tăng tốc ngay trong editor AI-first. Với Windsurf, góc chính là xem workflow kiểu agent có giảm phối hợp thủ công trong task lớn hay không. Đây là hai lời hứa khác nhau, nên CTA không nên xem chúng như sản phẩm thay thế y hệt nhau.",
    "The most trustworthy path is to send readers first to internal reviews and pricing checks, then to the tracked official-site CTA. That gives the visitor more context and gives the site cleaner internal linking around Cursor review, Windsurf review, Cursor pricing, and the AI coding tools category.": "Cách đáng tin hơn là dẫn người đọc qua review nội bộ và phần kiểm tra giá trước, sau đó mới tới CTA website chính thức có tracking. Cách này cho người đọc thêm ngữ cảnh và giúp site có internal linking sạch hơn quanh Cursor review, Windsurf review, Cursor pricing và danh mục AI coding tools.",
    "If this page is later updated with real hands-on notes, keep the structure but add task-level observations: what repository was used, which test failed, where each tool needed correction, and what kind of diff was finally accepted. Specificity is what separates a useful comparison from a thin affiliate page.": "Khi trang này được cập nhật bằng ghi chú hands-on thật, hãy giữ cấu trúc nhưng thêm quan sát ở cấp task: dùng repository nào, test nào fail, công cụ cần sửa ở đâu và diff cuối cùng được chấp nhận thuộc loại gì. Sự cụ thể là điểm tách một bài so sánh hữu ích khỏi trang affiliate mỏng.",
    "Choose Cursor if you want an AI-first editor that feels close to normal coding but adds strong assistance for explaining, editing, and refactoring code. It is especially useful for solo developers, technical founders, and small teams that can tolerate some workflow change in exchange for speed.": "Chọn Cursor nếu bạn muốn một editor AI-first vẫn gần với cách code bình thường nhưng hỗ trợ mạnh khi giải thích, chỉnh sửa và refactor code. Nó đặc biệt hợp với solo developer, founder kỹ thuật và team nhỏ có thể chấp nhận đổi workflow để lấy tốc độ.",
    "Choose Windsurf if you are specifically testing whether agentic coding workflows can reduce the back-and-forth of planning, editing, running commands, and fixing results. The best test is a multi-file task with a failing test, not a simple function generator.": "Chọn Windsurf nếu bạn muốn kiểm tra cụ thể liệu workflow code kiểu agent có giảm vòng lặp lập kế hoạch, chỉnh sửa, chạy lệnh và sửa lỗi sau đó hay không. Bài test tốt nhất là một task nhiều file có test đang fail, không phải yêu cầu tạo một function đơn giản.",
    "Choose GitHub Copilot if your team wants a familiar assistant inside existing IDEs; choose Cursor if you want an AI-first editor that changes how coding work is planned and executed.": "Chọn GitHub Copilot nếu team muốn một trợ lý quen thuộc trong IDE hiện có; chọn Cursor nếu bạn muốn một editor AI-first thay đổi cách lên kế hoạch và triển khai công việc code.",
    "This is a workflow decision, not a simple feature checklist. Copilot is usually easier to introduce inside organizations, while Cursor can feel more powerful for developers who want repository-aware AI at the center of their editor.": "Đây là quyết định về workflow, không phải checklist tính năng đơn giản. Copilot thường dễ đưa vào tổ chức hơn, còn Cursor có thể mạnh hơn với lập trình viên muốn AI hiểu repository nằm ngay trung tâm editor.",
    "This comparison focuses on context awareness, autocomplete speed, terminal and repository workflow, multi-file editing, pricing risk, onboarding difficulty, and when each tool is a poor fit.": "Bài so sánh này tập trung vào khả năng hiểu ngữ cảnh, tốc độ autocomplete, workflow terminal/repository, chỉnh sửa nhiều file, rủi ro giá, độ khó onboarding và khi nào từng công cụ không phù hợp.",
    "For affiliate content, the reader searching Copilot vs Cursor is usually already aware of both tools. The page should help them decide which one deserves a real test, not push both links with vague praise.": "Với nội dung affiliate, người tìm Copilot vs Cursor thường đã biết cả hai công cụ. Trang này nên giúp họ quyết định công cụ nào đáng test thật, không phải đẩy cả hai link bằng lời khen mơ hồ.",
    "The real decision: assistant layer or AI-first editor": "Quyết định thật: lớp trợ lý hay editor AI-first",
    "GitHub Copilot and Cursor solve overlapping problems from different starting points. Copilot is easier to understand as an assistant layer that fits into familiar developer environments. Cursor is more opinionated: the editor itself becomes part of the AI workflow, which can make context, chat, and edits feel more connected.": "GitHub Copilot và Cursor xử lý các vấn đề có phần trùng nhau nhưng bắt đầu từ hai hướng khác nhau. Copilot dễ hiểu hơn như một lớp trợ lý nằm trong môi trường lập trình quen thuộc. Cursor quyết liệt hơn: chính editor trở thành một phần của workflow AI, khiến context, chat và chỉnh sửa gắn với nhau hơn.",
    "For an enterprise team, Copilot often wins the first procurement conversation because it sits close to GitHub and Microsoft workflows. For a solo developer or technical founder, Cursor may feel more productive because it changes the daily coding loop more aggressively.": "Với team doanh nghiệp, Copilot thường thắng ở vòng trao đổi mua sắm đầu tiên vì nó gần với workflow GitHub và Microsoft. Với solo developer hoặc founder kỹ thuật, Cursor có thể tạo cảm giác năng suất hơn vì nó thay đổi vòng lặp code hằng ngày mạnh hơn.",
    "Enterprise adoption and developer autonomy": "Triển khai trong doanh nghiệp và quyền tự chủ của developer",
    "How to run a fair Copilot vs Cursor test": "Cách test Copilot vs Cursor công bằng",
    "Copilot vs Cursor is a high-intent query because it usually comes from someone who already accepts the value of AI coding assistance. The question is where that assistance should live. Copilot represents the safer assistant layer. Cursor represents a deeper change to the editor workflow. A useful page should make that tradeoff obvious in the first few sections.": "Copilot vs Cursor là truy vấn có intent cao vì người tìm thường đã chấp nhận giá trị của AI coding assistant. Câu hỏi là trợ lý đó nên nằm ở đâu trong workflow. Copilot đại diện cho lớp trợ lý an toàn hơn; Cursor là thay đổi sâu hơn vào chính editor. Một trang hữu ích cần làm rõ tradeoff này ngay từ các phần đầu.",
    "The conversion path should be different for each reader type. A developer who owns their own setup can go directly from this comparison to the Cursor review or Cursor pricing page. An engineering manager may need to read the GitHub Copilot review, compare team rollout risk, and then visit the official site for current plan details.": "Đường chuyển đổi nên khác nhau theo từng nhóm người đọc. Một developer tự quản workflow có thể đi thẳng từ bài so sánh này sang review Cursor hoặc trang giá Cursor. Một engineering manager có thể cần đọc review GitHub Copilot, so sánh rủi ro rollout cho team rồi mới vào website chính thức để kiểm tra gói hiện tại.",
    "A weak comparison would say both tools are good and leave the reader with no decision. A stronger recommendation says Copilot is the practical default for GitHub-centered teams, while Cursor is the stronger test for people who want AI to shape the coding loop itself.": "Một bài so sánh yếu sẽ nói cả hai công cụ đều tốt rồi để người đọc tự đoán. Khuyến nghị mạnh hơn là: Copilot là mặc định thực tế cho team xoay quanh GitHub, còn Cursor là lựa chọn đáng test hơn nếu bạn muốn AI định hình chính vòng lặp code.",
    "When this page is updated later, the best addition would be a real pilot table: setup time, accepted suggestions, reverted suggestions, test failures fixed, documentation quality, and developer confidence after one week. Those signals matter more than generic claims about speed.": "Khi cập nhật trang này sau, phần bổ sung giá trị nhất sẽ là bảng pilot thật: thời gian setup, số gợi ý được chấp nhận, số gợi ý phải revert, lỗi test đã sửa, chất lượng tài liệu và độ tự tin của developer sau một tuần. Những tín hiệu này quan trọng hơn các tuyên bố chung chung về tốc độ.",
    "Until that pilot data exists, the responsible recommendation is to run a small controlled trial, keep human review mandatory, and choose the workflow that reduces review friction rather than the one that writes the most code.": "Cho đến khi có dữ liệu pilot đó, khuyến nghị có trách nhiệm là chạy thử nhỏ có kiểm soát, giữ human review bắt buộc và chọn workflow giảm ma sát review thay vì chọn công cụ viết nhiều code nhất.",
    "Visit Cursor": "Truy cập Cursor",
    "Visit Windsurf": "Truy cập Windsurf",
    "Visit GitHub Copilot": "Truy cập GitHub Copilot",
    "Read AI coding guide": "Đọc hướng dẫn AI coding",
    "Compare Cursor and Windsurf": "So sánh Cursor và Windsurf",
}


def localize_html(text: str) -> str:
    """Normalize common generated UI labels to Vietnamese.

    This is intentionally conservative: it targets repeated template copy and
    known mojibake strings without changing brand names or URLs.
    """
    for source, target in MOJIBAKE_REPLACEMENTS.items():
        text = text.replace(source, target)
    text = text.replace('<html lang="en">', '<html lang="vi">')
    text = text.replace("<html lang='en'>", "<html lang='vi'>")
    for source, target in PHRASE_REPLACEMENTS.items():
        text = text.replace(source, target)
    for source, target in PAGE_TEXT_REPLACEMENTS.items():
        text = text.replace(source, target)
    # Replace longer UI strings before short words to avoid partial conflicts.
    for source, target in sorted(UI_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)

    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Review: Features, Pros, Cons, Pricing Notes",
        lambda m: f"{m.group(1).strip()} Đánh giá: tính năng, ưu điểm, hạn chế và ghi chú giá",
        text,
    )
    text = re.sub(
        r">([A-Za-z0-9 .+&-]+) Đánh giá<",
        lambda m: f">Đánh giá {m.group(1).strip()}<",
        text,
    )
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Đánh giá: tính năng",
        lambda m: f"Đánh giá {m.group(1).strip()}: tính năng",
        text,
    )
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Pricing Guide: Plans, Trial Notes, and Buying Risks",
        lambda m: f"Hướng dẫn giá {m.group(1).strip()}: gói dịch vụ, dùng thử và rủi ro khi mua",
        text,
    )
    # Keep JSON-LD schema type values machine-readable after visible UI translation.
    text = text.replace('"@type": "Câu hỏi thường gặpPage"', '"@type": "FAQPage"')
    text = text.replace('"@type":"Câu hỏi thường gặpPage"', '"@type":"FAQPage"')
    text = text.replace('"@type": "Đánh giá"', '"@type": "Review"')
    text = text.replace('"@type":"Đánh giá"', '"@type":"Review"')
    return text
