from __future__ import annotations

import re


MOJIBAKE_REPLACEMENTS = {
    "PhÃ¹ há»£p vá»›i": "Phù hợp với",
    "KhÃ´ng phÃ¹ há»£p náº¿u": "Không phù hợp nếu",
    "Khi nÃ o nÃªn dÃ¹ng?": "Khi nào nên dùng?",
    "Khi nÃ o KHÃ”NG nÃªn dÃ¹ng?": "Khi nào KHÔNG nên dùng?",
    "Workflow phÃ¹ há»£p": "Workflow phù hợp",
    "Äá»‘i tÆ°á»£ng phÃ¹ há»£p nháº¥t": "Đối tượng phù hợp nhất",
    "CÃ´ng cá»¥ nÃ y giáº£i quyáº¿t viá»‡c gÃ¬?": "Công cụ này giải quyết việc gì?",
    "Ai nÃªn cÃ¢n nháº¯c?": "Ai nên cân nhắc?",
    "TÃ­nh nÄƒng Ä‘Ã¡ng chÃº Ã½": "Tính năng đáng chú ý",
    "Äiá»ƒm máº¡nh ná»•i báº­t": "Điểm mạnh nổi bật",
    "Äiá»ƒm gÃ¢y khÃ³ chá»‹u": "Điểm gây khó chịu",
    "Æ¯u Ä‘iá»ƒm": "Ưu điểm",
    "NhÆ°á»£c Ä‘iá»ƒm / háº¡n cháº¿": "Nhược điểm / hạn chế",
    "Báº£ng Æ°u Ä‘iá»ƒm / háº¡n cháº¿": "Bảng ưu điểm / hạn chế",
    "Giáº£i thÃ­ch Ä‘iá»ƒm sá»‘": "Giải thích điểm số",
    "Ghi chÃº pricing": "Ghi chú giá",
    "HÃ£y xÃ¡c minh giÃ¡ hiá»‡n táº¡i trÃªn website chÃ­nh thá»©c.": "Hãy xác minh giá hiện tại trên website chính thức.",
    "Pricing, trial, giá»›i háº¡n plan vÃ  Ä‘iá»u khoáº£n há»§y cÃ³ thá»ƒ thay Ä‘á»•i theo thá»i gian.": "Giá, bản dùng thử, giới hạn gói và điều khoản hủy có thể thay đổi theo thời gian.",
    "TÃ³m táº¯t pricing": "Tóm tắt giá",
    "Review nghiÃªn cá»©u vá»": "Review nghiên cứu về",
    "Ä‘iá»ƒm máº¡nh": "điểm mạnh",
    "háº¡n cháº¿": "hạn chế",
    "vÃ  affiliate disclosure": "và tiết lộ liên kết",
    "á»Ÿ website chÃ­nh thá»©c": "ở website chính thức",
    "âœ“ Pros": "Ưu điểm",
    "âš  Cons": "Hạn chế",
}


UI_REPLACEMENTS = {
    "AI Tool Review Center": "Trung tâm đánh giá công cụ AI",
    "AI Tool": "Công cụ AI",
    "Review": "Đánh giá",
    "Independent-style reviews": "Đánh giá độc lập theo hướng nghiên cứu",
    "Some links may be affiliate links. We may earn a commission at no extra cost to you.": "Một số liên kết có thể là liên kết tiếp thị liên kết. Chúng tôi có thể nhận hoa hồng mà không phát sinh thêm chi phí cho bạn.",
    "Some links may be affiliate links. We may earn a commission at no extra cost to you": "Một số liên kết có thể là liên kết tiếp thị liên kết. Chúng tôi có thể nhận hoa hồng mà không phát sinh thêm chi phí cho bạn",
    "This review is for research purposes only.": "Bài đánh giá này chỉ phục vụ mục đích nghiên cứu.",
    "We may earn commission if you purchase through our links. This does not change your price.": "Chúng tôi có thể nhận hoa hồng nếu bạn mua qua liên kết của chúng tôi. Điều này không làm thay đổi giá bạn trả.",
    "Reviews are for research purposes only.": "Các bài đánh giá chỉ nhằm mục đích nghiên cứu.",
    "Home": "Trang chủ",
    "Reviews": "Đánh giá",
    "Comparisons": "So sánh",
    "Pricing": "Giá",
    "Categories": "Danh mục",
    "Hubs": "Trung tâm",
    "Contact": "Liên hệ",
    "Privacy Policy": "Chính sách bảo mật",
    "Terms": "Điều khoản",
    "Disclosure": "Tiết lộ liên kết",
    "Affiliate Disclosure": "Tiết lộ liên kết",
    "About": "Giới thiệu",
    "About Author": "Giới thiệu tác giả",
    "Editorial Policy": "Chính sách biên tập",
    "Testing Methodology": "Phương pháp thử nghiệm",
    "Contents": "Nội dung",
    "Overview": "Tổng quan",
    "Features": "Tính năng",
    "Pros and Cons": "Ưu điểm và hạn chế",
    "Who Should Use It": "Ai nên dùng?",
    "Alternatives": "Lựa chọn thay thế",
    "FAQ": "Câu hỏi thường gặp",
    "Final Verdict": "Kết luận cuối",
    "Final verdict": "Kết luận cuối",
    "Final recommendation": "Khuyến nghị cuối",
    "Short answer:": "Tóm tắt nhanh:",
    "Visit Official Website": "Truy cập website chính thức",
    "Verify Current Pricing": "Kiểm tra giá hiện tại",
    "Check current pricing": "Kiểm tra giá hiện tại",
    "Affiliate link pending approval.": "Liên kết tiếp thị đang chờ phê duyệt.",
    "Rating Summary": "Tóm tắt điểm đánh giá",
    "Featured image placeholder": "Ảnh minh họa",
    "research overview": "tổng quan nghiên cứu",
    "Ease of use": "Dễ sử dụng",
    "Features": "Tính năng",
    "Best for": "Phù hợp nhất",
    "teams comparing SaaS tools": "nhóm đang so sánh công cụ SaaS",
    "Last updated:": "Cập nhật lần cuối:",
    "Share:": "Chia sẻ:",
    "Affiliate disclosure:": "Tiết lộ liên kết:",
    "Affiliate disclosure": "Tiết lộ liên kết",
    "Affiliate link field": "Trạng thái liên kết tiếp thị",
    "Status:": "Trạng thái:",
    "CTA URL used now:": "URL CTA đang dùng:",
    "Replace this with an approved affiliate link only after the affiliate program approves your account. Do not use fake affiliate links.": "Chỉ thay bằng link affiliate thật sau khi chương trình tiếp thị liên kết phê duyệt tài khoản. Không dùng link affiliate giả.",
    "Comparison table": "Bảng so sánh",
    "Feature comparison table": "Bảng so sánh tính năng",
    "Pricing comparison": "So sánh giá",
    "Pricing summary": "Tóm tắt giá",
    "Pricing note": "Ghi chú giá",
    "Pricing Guides": "Hướng dẫn giá",
    "Pricing Guide": "Hướng dẫn giá",
    "Pricing research": "Nghiên cứu giá",
    "Tool": "Công cụ",
    "Pricing type": "Kiểu giá",
    "Pros": "Ưu điểm",
    "Cons": "Hạn chế",
    "Best alternatives": "Lựa chọn thay thế tốt",
    "Good alternatives depend on your budget, workflow and required integrations. Compare at least two or three tools before buying.": "Lựa chọn thay thế phù hợp phụ thuộc vào ngân sách, workflow và tích hợp bạn cần. Nên so sánh ít nhất hai hoặc ba công cụ trước khi mua.",
    "How we tested": "Cách chúng tôi đánh giá",
    "Internal links for deeper research": "Liên kết nội bộ để nghiên cứu sâu hơn",
    "Related comparisons": "So sánh liên quan",
    "Alternatives and similar tools": "Lựa chọn thay thế và công cụ tương tự",
    "Related research": "Nội dung liên quan",
    "Related reviews": "Đánh giá liên quan",
    "Popular reviews": "Đánh giá phổ biến",
    "Popular comparisons": "So sánh phổ biến",
    "Pricing pages": "Trang giá",
    "Pricing research": "Nghiên cứu giá",
    "Top lists": "Danh sách nổi bật",
    "Top categories": "Danh mục nổi bật",
    "Best category pages": "Trang danh mục phù hợp",
    "Best category page": "Trang danh mục phù hợp",
    "Alternatives and related tools": "Lựa chọn thay thế và công cụ liên quan",
    "Reviews in this category": "Đánh giá trong danh mục này",
    "Comparison pages": "Trang so sánh",
    "Related pricing pages": "Trang giá liên quan",
    "Related hubs": "Trung tâm liên quan",
    "Priority pages": "Trang ưu tiên",
    "Author": "Tác giả",
    "Independent AI & SaaS Researcher": "Người nghiên cứu AI & SaaS độc lập",
    "Researching AI tools, SaaS software, automation systems, and productivity workflows.": "Nghiên cứu công cụ AI, phần mềm SaaS, hệ thống tự động hóa và workflow năng suất.",
    "Research methodology": "Phương pháp nghiên cứu",
    "Tested feature review": "Đánh giá tính năng đã kiểm tra",
    "Public pricing review": "Kiểm tra thông tin giá công khai",
    "UI evaluation": "Đánh giá giao diện",
    "Workflow comparison": "So sánh workflow",
    "User feedback research": "Nghiên cứu phản hồi người dùng",
    "Get new AI tool reviews and comparisons.": "Nhận cập nhật review và so sánh công cụ AI mới.",
    "Join the research list for new AI/SaaS review updates. No backend is connected yet; this placeholder is ready for a future email provider.": "Theo dõi các cập nhật review AI/SaaS mới. Hiện chưa kết nối backend email; phần này sẵn sàng để tích hợp nhà cung cấp email sau.",
    "Notify me": "Thông báo cho tôi",
    "Compare now": "So sánh ngay",
    "See alternatives": "Xem lựa chọn thay thế",
    "Compare more tools": "So sánh thêm công cụ",
    "Browse reviews": "Xem danh sách đánh giá",
    "Read review": "Đọc đánh giá",
    "Read related reviews": "Đọc đánh giá liên quan",
    "Compare tools": "So sánh công cụ",
    "Browse comparisons": "Xem các bài so sánh",
    "All comparisons": "Tất cả bài so sánh",
    "All reviews": "Tất cả bài đánh giá",
    "Check pricing guides": "Xem hướng dẫn giá",
    "Explore categories": "Khám phá danh mục",
    "Related category": "Danh mục liên quan",
    "Next step": "Bước tiếp theo",
    "What to verify": "Cần xác minh",
    "Risk signal": "Tín hiệu rủi ro",
    "Area": "Tiêu chí",
    "Best fit": "Phù hợp nhất",
    "Context awareness": "Hiểu ngữ cảnh",
    "Autocomplete feel": "Cảm giác autocomplete",
    "Multi-file editing": "Chỉnh sửa nhiều file",
    "Pricing risk": "Rủi ro giá",
    "Tool posture": "Định vị công cụ",
    "Enterprise fit": "Phù hợp doanh nghiệp",
    "Editor workflow": "Workflow trong editor",
    "Autocomplete speed": "Tốc độ autocomplete",
    "Weaknesses": "Điểm yếu",
    "Strengths": "Điểm mạnh",
    "Quick comparison": "So sánh nhanh",
    "Pros and cons": "Ưu điểm và hạn chế",
    "Best use case": "Use case phù hợp nhất",
    "Who should avoid": "Ai không nên dùng?",
}


PHRASE_REPLACEMENTS = {
    "Clear category fit for comparison content.": "Phù hợp rõ với nội dung so sánh trong cùng danh mục.",
    "High buyer intent signal.": "Có tín hiệu ý định mua cao.",
    "Positive estimated ROI signal, pending real campaign data.": "Có tín hiệu ROI dự kiến tích cực, nhưng vẫn cần dữ liệu chiến dịch thật.",
    "Pricing and terms must be checked on the official website.": "Cần kiểm tra giá và điều khoản trên website chính thức.",
    "Direct affiliate linking should be avoided unless terms allow it.": "Không nên dùng link affiliate trực tiếp trừ khi điều khoản cho phép.",
    "Trademark bidding should be avoided.": "Không nên bid từ khóa thương hiệu.",
    "Current data confidence is low and needs manual verification.": "Độ tin cậy dữ liệu hiện còn thấp và cần kiểm tra thủ công.",
    "Core workflow support for AI Coding.": "Hỗ trợ workflow chính cho AI Coding.",
    "Useful for review, comparison and product research workflows.": "Hữu ích cho workflow đánh giá, so sánh và nghiên cứu sản phẩm.",
    "Requires official pricing and policy verification before paid promotion.": "Cần xác minh giá và chính sách chính thức trước khi quảng bá trả phí.",
    "Pricing can change. Use this review as a research starting point and confirm the latest plan limits, trial terms, cancellation terms, and commercial usage rules on the official website.": "Giá có thể thay đổi. Hãy xem bài review này như điểm bắt đầu nghiên cứu và xác minh giới hạn gói, điều khoản dùng thử, điều khoản hủy và quyền sử dụng thương mại mới nhất trên website chính thức.",
    "Reviewed the public product positioning and feature set.": "Đã xem xét định vị sản phẩm công khai và bộ tính năng.",
    "Compared the tool against category alternatives.": "Đã so sánh công cụ với các lựa chọn cùng danh mục.",
    "Checked pricing and policy areas that require manual verification.": "Đã kiểm tra các phần giá và chính sách cần xác minh thủ công.",
    "Evaluated workflow fit for realistic business use cases.": "Đã đánh giá mức phù hợp workflow cho các use case kinh doanh thực tế.",
    "May fit different workflows": "Có thể phù hợp với workflow khác",
    "Requires separate verification": "Cần xác minh riêng",
    "Teams comparing": "Nhóm đang so sánh",
    "Budget-sensitive buyers": "Người mua nhạy cảm với ngân sách",
    "May offer simpler entry plan": "Có thể có gói khởi đầu đơn giản hơn",
    "Feature depth may differ": "Độ sâu tính năng có thể khác",
    "Check official pricing.": "Kiểm tra giá trên website chính thức.",
    "Check official pricing": "Kiểm tra giá chính thức",
    "Check official pricing for both tools before buying, writing affiliate content, or sending paid traffic.": "Hãy kiểm tra giá chính thức của cả hai công cụ trước khi mua, viết nội dung affiliate hoặc chạy traffic trả phí.",
    "Also compare related reviews and broader category pages before deciding.": "Nên so sánh thêm các bài review liên quan và trang danh mục rộng hơn trước khi quyết định.",
}


PAGE_TEXT_REPLACEMENTS = {
    "Introduction": "Giới thiệu",
    "Cursor vs Windsurf: Which AI Coding Editor Fits Real Development Work?": "Cursor vs Windsurf: trình soạn thảo AI nào phù hợp với workflow lập trình thực tế?",
    "Cursor vs Windsurf: Which AI Coding Editor Should You Test First?": "Cursor vs Windsurf: nên thử trình soạn thảo mã AI nào trước?",
    "Copilot vs Cursor: Enterprise Assistant or AI-First Coding Editor?": "Copilot vs Cursor: trợ lý doanh nghiệp hay trình soạn thảo AI-first?",
    "Copilot vs Cursor: Which AI Coding Workflow Makes More Sense?": "Copilot vs Cursor: workflow lập trình AI nào hợp lý hơn?",
    "Cursor is the better first test if you want a controlled AI-first coding editor; Windsurf is the more interesting test if you want to explore agent-style coding workflows.": "Cursor là lựa chọn nên thử trước nếu bạn muốn một trình soạn thảo AI-first dễ kiểm soát; Windsurf đáng thử nếu bạn muốn khám phá workflow lập trình kiểu agent.",
    "The real question is not which product has the better demo. The real question is which tool helps you understand, edit, test, and review code with less friction inside your own repository.": "Câu hỏi thực sự không phải sản phẩm nào có demo đẹp hơn. Câu hỏi thực tế là công cụ nào giúp bạn hiểu, chỉnh sửa, kiểm thử và review code ít ma sát hơn ngay trong repository của mình.",
    "This comparison focuses on context awareness, autocomplete behavior, terminal integration, multi-file editing, pricing risk, onboarding difficulty, and when a developer should avoid either option.": "Bài so sánh này tập trung vào khả năng hiểu ngữ cảnh, autocomplete, tích hợp terminal, chỉnh sửa nhiều file, rủi ro giá, độ khó khi làm quen và khi nào lập trình viên nên tránh từng lựa chọn.",
    "For affiliate and SEO content, this is a high-intent page because readers searching Cursor vs Windsurf are usually close to testing one of the tools. The recommendation should be specific, cautious, and useful rather than aggressively promotional.": "Với nội dung SEO/affiliate, đây là trang có intent cao vì người tìm Cursor vs Windsurf thường đã gần đến bước thử một trong hai công cụ. Khuyến nghị cần cụ thể, thận trọng và hữu ích thay vì quảng bá quá đà.",
    "Where the comparison actually matters": "Điểm so sánh thực sự quan trọng",
    "Cursor and Windsurf are not just autocomplete tools. They are competing ideas about how much of the coding workflow should live inside an AI-assisted editor. The important questions are practical: does the tool understand the codebase, can it safely edit multiple files, does it recover when the first plan is wrong, and how much manual cleanup remains after the assistant finishes.": "Cursor và Windsurf không chỉ là công cụ autocomplete. Chúng đại diện cho hai cách nghĩ khác nhau về việc bao nhiêu phần của workflow lập trình nên nằm trong một editor có AI hỗ trợ. Câu hỏi quan trọng rất thực tế: công cụ có hiểu codebase không, có chỉnh sửa nhiều file an toàn không, có phục hồi được khi kế hoạch đầu sai không, và sau khi AI hoàn tất thì còn phải dọn thủ công bao nhiêu.",
    "Cursor feels strongest when a developer wants tight control and fast movement inside a familiar AI-first editor. Windsurf is interesting when the workflow leans more toward agentic steps and guided changes. I would not judge either tool from a blank-file demo; use an existing repository with tests, config files, and messy naming conventions.": "Cursor mạnh nhất khi lập trình viên muốn kiểm soát chặt và di chuyển nhanh trong một editor AI-first quen tay. Windsurf thú vị hơn khi workflow nghiêng về các bước kiểu agent và thay đổi có hướng dẫn. Không nên đánh giá hai công cụ bằng demo file trống; hãy dùng một repository thật có test, file cấu hình và quy ước đặt tên lộn xộn.",
    "Recommendation after a one-week pilot": "Khuyến nghị sau một tuần thử nghiệm",
    "If a one-week pilot shows Cursor reducing time spent on codebase exploration and small refactors, I would keep Cursor as the main editor for individual developer workflows. It is most persuasive when the developer can point to specific tasks that became easier, not just a general feeling that AI is faster.": "Nếu một tuần thử nghiệm cho thấy Cursor giảm thời gian đọc codebase và refactor nhỏ, tôi sẽ giữ Cursor làm editor chính cho workflow cá nhân. Tín hiệu thuyết phục nhất là lập trình viên chỉ ra được task cụ thể đã dễ hơn, không chỉ cảm giác chung chung rằng AI nhanh hơn.",
    "If Windsurf handles multi-step changes with fewer manual resets, it becomes a stronger candidate for developers who want a more agentic coding loop. The key metric is not how much code it writes. The key metric is how much of that code survives review after tests and human inspection.": "Nếu Windsurf xử lý các thay đổi nhiều bước với ít lần phải reset thủ công hơn, nó trở thành ứng viên mạnh cho người muốn vòng lặp lập trình kiểu agent. Thước đo chính không phải nó viết bao nhiêu code, mà là bao nhiêu phần code đó qua được review sau khi chạy test và kiểm tra thủ công.",
    "If neither tool clearly improves the workflow, stay with the existing editor and test GitHub Copilot or another assistant layer. The best outcome of a pilot is not always buying a tool; sometimes it is learning that the team needs better tests, clearer tickets, or smaller pull requests before AI coding tools can help.": "Nếu không công cụ nào cải thiện workflow rõ ràng, hãy giữ editor hiện tại và thử GitHub Copilot hoặc một lớp trợ lý nhẹ hơn. Kết quả tốt nhất của một đợt thử nghiệm không phải lúc nào cũng là mua tool; đôi khi là nhận ra team cần test tốt hơn, ticket rõ hơn hoặc pull request nhỏ hơn trước khi AI coding tool thật sự giúp được.",
    "Search intent and conversion notes": "Ý định tìm kiếm và ghi chú chuyển đổi",
    "A reader searching Cursor vs Windsurf is usually not at the top of the funnel. They already know both names and are trying to understand which one deserves a trial. That makes the page useful for affiliate conversion, but only if the recommendation feels earned. The content should help the reader choose a test path, not pressure them into clicking both official sites.": "Người tìm Cursor vs Windsurf thường không còn ở đầu phễu. Họ đã biết cả hai tên và đang muốn hiểu công cụ nào đáng thử. Điều đó khiến trang này có giá trị cho affiliate conversion, nhưng chỉ khi khuyến nghị có lý do rõ ràng. Nội dung nên giúp người đọc chọn hướng test, không ép họ bấm cả hai website chính thức.",
    "For Cursor, the conversion angle is control and immediate productivity inside an AI-first editor. For Windsurf, the angle is exploring whether agent-style coding can reduce manual coordination during larger tasks. These are different promises, so the CTA copy should not treat them as interchangeable products.": "Với Cursor, góc chuyển đổi là khả năng kiểm soát và tăng tốc ngay trong editor AI-first. Với Windsurf, góc chính là xem workflow kiểu agent có giảm phối hợp thủ công trong task lớn hay không. Đây là hai lời hứa khác nhau, nên CTA không nên xem chúng như sản phẩm thay thế y hệt nhau.",
    "The most trustworthy path is to send readers first to internal reviews and pricing checks, then to the tracked official-site CTA. That gives the visitor more context and gives the site cleaner internal linking around Cursor review, Windsurf review, Cursor pricing, and the AI coding tools category.": "Cách đáng tin hơn là dẫn người đọc qua review nội bộ và phần kiểm tra giá trước, sau đó mới tới CTA website chính thức có tracking. Cách này cho người đọc thêm ngữ cảnh và giúp site có internal linking sạch hơn quanh Cursor review, Windsurf review, Cursor pricing và danh mục AI coding tools.",
    "If this page is later updated with real hands-on notes, keep the structure but add task-level observations: what repository was used, which test failed, where each tool needed correction, and what kind of diff was finally accepted. Specificity is what separates a useful comparison from a thin affiliate page.": "Khi trang này được cập nhật bằng ghi chú hands-on thật, hãy giữ cấu trúc nhưng thêm quan sát ở cấp task: dùng repository nào, test nào fail, công cụ cần sửa ở đâu và diff cuối cùng được chấp nhận thuộc loại gì. Sự cụ thể là điểm tách một bài so sánh hữu ích khỏi trang affiliate mỏng.",
    "Choose Cursor if you want an AI-first editor that feels close to normal coding but adds strong assistance for explaining, editing, and refactoring code. It is especially useful for solo developers, technical founders, and small teams that can tolerate some workflow change in exchange for speed.": "Chọn Cursor nếu bạn muốn một editor AI-first vẫn gần với cách code bình thường nhưng hỗ trợ mạnh khi giải thích, chỉnh sửa và refactor code. Nó đặc biệt hợp với solo developer, founder kỹ thuật và team nhỏ có thể chấp nhận đổi workflow để lấy tốc độ.",
    "Choose Windsurf if you are specifically testing whether agentic coding workflows can reduce the back-and-forth of planning, editing, running commands, and fixing results. The best test is a multi-file task with a failing test, not a simple function generator.": "Chọn Windsurf nếu bạn muốn kiểm tra cụ thể liệu workflow code kiểu agent có giảm vòng lặp lập kế hoạch, chỉnh sửa, chạy lệnh và sửa lỗi sau đó hay không. Bài test tốt nhất là một task nhiều file có test đang fail, không phải yêu cầu tạo một function đơn giản.",
    "Choose GitHub Copilot if your team wants a familiar assistant inside existing IDEs; choose Cursor if you want an AI-first editor that changes how coding work is planned and executed.": "Chọn GitHub Copilot nếu team muốn một trợ lý quen thuộc trong IDE hiện có; chọn Cursor nếu bạn muốn một editor AI-first thay đổi cách lên kế hoạch và triển khai công việc code.",
    "This is a workflow decision, not a simple feature checklist. Copilot is usually easier to introduce inside organizations, while Cursor can feel more powerful for developers who want repository-aware AI at the center of their editor.": "Đây là quyết định về workflow, không phải checklist tính năng đơn giản. Copilot thường dễ đưa vào tổ chức hơn, còn Cursor có thể mạnh hơn với lập trình viên muốn AI hiểu repository nằm ngay trung tâm editor.",
    "This comparison focuses on context awareness, autocomplete speed, terminal and repository workflow, multi-file editing, pricing risk, onboarding difficulty, and when each tool is a poor fit.": "Bài so sánh này tập trung vào khả năng hiểu ngữ cảnh, tốc độ autocomplete, workflow terminal/repository, chỉnh sửa nhiều file, rủi ro giá, độ khó onboarding và khi nào từng công cụ không phù hợp.",
    "For affiliate content, the reader searching Copilot vs Cursor is usually already aware of both tools. The page should help them decide which one deserves a real test, not push both links with vague praise.": "Với nội dung affiliate, người tìm Copilot vs Cursor thường đã biết cả hai công cụ. Trang này nên giúp họ quyết định công cụ nào đáng test thật, không phải đẩy cả hai link bằng lời khen mơ hồ.",
    "The real decision: assistant layer or AI-first editor": "Quyết định thật: lớp trợ lý hay editor AI-first",
    "GitHub Copilot and Cursor solve overlapping problems from different starting points. Copilot is easier to understand as an assistant layer that fits into familiar developer environments. Cursor is more opinionated: the editor itself becomes part of the AI workflow, which can make context, chat, and edits feel more connected.": "GitHub Copilot và Cursor xử lý các vấn đề có phần trùng nhau nhưng bắt đầu từ hai hướng khác nhau. Copilot dễ hiểu hơn như một lớp trợ lý nằm trong môi trường lập trình quen thuộc. Cursor quyết liệt hơn: chính editor trở thành một phần của workflow AI, khiến context, chat và chỉnh sửa gắn với nhau hơn.",
    "For an enterprise team, Copilot often wins the first procurement conversation because it sits close to GitHub and Microsoft workflows. For a solo developer or technical founder, Cursor may feel more productive because it changes the daily coding loop more aggressively.": "Với team doanh nghiệp, Copilot thường thắng ở vòng trao đổi mua sắm đầu tiên vì nó gần với workflow GitHub và Microsoft. Với solo developer hoặc founder kỹ thuật, Cursor có thể tạo cảm giác năng suất hơn vì nó thay đổi vòng lặp code hằng ngày mạnh hơn.",
    "Enterprise adoption and developer autonomy": "Triển khai trong doanh nghiệp và quyền tự chủ của developer",
    "How to run a fair Copilot vs Cursor test": "Cách test Copilot vs Cursor công bằng",
    "Copilot vs Cursor is a high-intent query because it usually comes from someone who already accepts the value of AI coding assistance. The question is where that assistance should live. Copilot represents the safer assistant layer. Cursor represents a deeper change to the editor workflow. A useful page should make that tradeoff obvious in the first few sections.": "Copilot vs Cursor là truy vấn có intent cao vì người tìm thường đã chấp nhận giá trị của AI coding assistant. Câu hỏi là trợ lý đó nên nằm ở đâu trong workflow. Copilot đại diện cho lớp trợ lý an toàn hơn; Cursor là thay đổi sâu hơn vào chính editor. Một trang hữu ích cần làm rõ tradeoff này ngay từ các phần đầu.",
    "The conversion path should be different for each reader type. A developer who owns their own setup can go directly from this comparison to the Cursor review or Cursor pricing page. An engineering manager may need to read the GitHub Copilot review, compare team rollout risk, and then visit the official site for current plan details.": "Đường chuyển đổi nên khác nhau theo từng nhóm người đọc. Một developer tự quản workflow có thể đi thẳng từ bài so sánh này sang review Cursor hoặc trang giá Cursor. Một engineering manager có thể cần đọc review GitHub Copilot, so sánh rủi ro rollout cho team rồi mới vào website chính thức để kiểm tra gói hiện tại.",
    "A weak comparison would say both tools are good and leave the reader with no decision. A stronger recommendation says Copilot is the practical default for GitHub-centered teams, while Cursor is the stronger test for people who want AI to shape the coding loop itself.": "Một bài so sánh yếu sẽ nói cả hai công cụ đều tốt rồi để người đọc tự đoán. Khuyến nghị mạnh hơn là: Copilot là mặc định thực tế cho team xoay quanh GitHub, còn Cursor là lựa chọn đáng test hơn nếu bạn muốn AI định hình chính vòng lặp code.",
    "When this page is updated later, the best addition would be a real pilot table: setup time, accepted suggestions, reverted suggestions, test failures fixed, documentation quality, and developer confidence after one week. Those signals matter more than generic claims about speed.": "Khi cập nhật trang này sau, phần bổ sung giá trị nhất sẽ là bảng pilot thật: thời gian setup, số gợi ý được chấp nhận, số gợi ý phải revert, lỗi test đã sửa, chất lượng tài liệu và độ tự tin của developer sau một tuần. Những tín hiệu này quan trọng hơn các tuyên bố chung chung về tốc độ.",
    "Until that pilot data exists, the responsible recommendation is to run a small controlled trial, keep human review mandatory, and choose the workflow that reduces review friction rather than the one that writes the most code.": "Cho đến khi có dữ liệu pilot đó, khuyến nghị có trách nhiệm là chạy thử nhỏ có kiểm soát, giữ human review bắt buộc và chọn workflow giảm ma sát review thay vì chọn công cụ viết nhiều code nhất.",
    "Visit Cursor": "Truy cập Cursor",
    "Visit Windsurf": "Truy cập Windsurf",
    "Visit GitHub Copilot": "Truy cập GitHub Copilot",
    "Read AI coding guide": "Đọc hướng dẫn AI coding",
    "Compare Cursor and Windsurf": "So sánh Cursor và Windsurf",
    "Teams that want AI assistance inside established IDE and GitHub workflows.": "Team muốn dùng AI hỗ trợ ngay trong IDE và workflow GitHub quen thuộc.",
    "Developers who want an AI-first editor for repository-aware coding.": "Developer muốn editor AI-first có khả năng hiểu repository tốt hơn.",
    "Enterprise comfort": "Mức dễ triển khai trong doanh nghiệp",
    "Generally stronger because many organizations already know GitHub procurement and policy.": "Thường dễ triển khai hơn vì nhiều tổ chức đã quen quy trình mua sắm và chính sách GitHub.",
    "Can be strong, but teams must evaluate editor adoption and policy fit.": "Có thể mạnh, nhưng team cần đánh giá khả năng chuyển editor và độ phù hợp chính sách.",
    "Context workflow": "Workflow theo ngữ cảnh",
    "Helpful assistant behavior, especially when integrated into existing development habits.": "Hữu ích như một lớp trợ lý, nhất là khi đã tích hợp vào thói quen phát triển hiện có.",
    "Often stronger when the task needs deeper editor-level context and multi-file iteration.": "Thường mạnh hơn khi task cần ngữ cảnh sâu trong editor và chỉnh sửa nhiều file.",
    "Familiar, widely adopted, and useful for everyday suggestions.": "Quen thuộc, phổ biến và hữu ích cho các gợi ý hằng ngày.",
    "Feels more integrated with AI chat and codebase editing workflows.": "Cho cảm giác gắn chặt hơn với chat AI và workflow chỉnh sửa codebase.",
    "Check seats, business plans, policy controls, and included features.": "Kiểm tra số seat, gói business, quyền kiểm soát chính sách và tính năng đi kèm.",
    "Check usage limits, model access, team seats, and editor migration cost.": "Kiểm tra giới hạn sử dụng, quyền truy cập model, seat team và chi phí chuyển editor.",
    "Solo developers and small teams that want an AI-first editor with strong repository context.": "Solo developer và team nhỏ muốn editor AI-first có ngữ cảnh repository mạnh.",
    "Developers exploring agent-style coding workflows and multi-step changes.": "Developer muốn thử workflow lập trình kiểu agent và các thay đổi nhiều bước.",
    "Strong when the right files are included and the developer guides the task clearly.": "Mạnh khi chọn đúng file liên quan và developer hướng dẫn task rõ ràng.",
    "Worth testing for broader workflow awareness and agent-style task handling.": "Đáng thử nếu muốn kiểm tra khả năng hiểu workflow rộng hơn và xử lý task kiểu agent.",
    "Often feels quick and editor-native for day-to-day coding.": "Thường nhanh và tự nhiên trong editor cho công việc code hằng ngày.",
    "More interesting when the task requires guided changes rather than only line completion.": "Thú vị hơn khi task cần thay đổi có hướng dẫn thay vì chỉ hoàn thành từng dòng.",
    "Useful for refactors, tests, and codebase navigation, but still requires review.": "Hữu ích cho refactor, test và điều hướng codebase, nhưng vẫn cần review kỹ.",
    "Potentially strong for broader agent workflows, but test on your own repository.": "Có tiềm năng mạnh với workflow agent rộng hơn, nhưng nên test trên repository của bạn.",
    "Verify usage limits, plan features, team seats, and model access.": "Xác minh giới hạn sử dụng, tính năng từng gói, seat team và quyền truy cập model.",
    "Verify plan maturity, limits, billing model, and cancellation rules.": "Xác minh độ hoàn thiện của gói, giới hạn, mô hình tính phí và điều khoản hủy.",
    "Use this page as editorial research. Verify pricing, limits, affiliate policy, and official terms before buying or promoting any tool.": "Hãy xem trang này như tài liệu nghiên cứu biên tập. Cần xác minh giá, giới hạn, chính sách affiliate và điều khoản chính thức trước khi mua hoặc quảng bá bất kỳ công cụ nào.",
    "Do not compare GitHub Copilot and Cursor only by a headline monthly price.": "Đừng so sánh GitHub Copilot và Cursor chỉ bằng giá tháng hiển thị ở trang bán hàng.",
    "For Copilot, check business plan features, organization controls, seat management, and GitHub ecosystem fit.": "Với Copilot, hãy kiểm tra tính năng gói business, kiểm soát tổ chức, quản lý seat và mức phù hợp với hệ sinh thái GitHub.",
    "For Cursor, check usage limits, model access, team collaboration features, and whether developers will actually adopt the editor.": "Với Cursor, hãy kiểm tra giới hạn sử dụng, quyền truy cập model, tính năng cộng tác team và liệu developer có thật sự chấp nhận editor này không.",
    "A practical trial should measure time saved, review quality, developer satisfaction, and failed suggestions.": "Một đợt thử nghiệm thực tế nên đo thời gian tiết kiệm được, chất lượng review, mức hài lòng của developer và số gợi ý bị sai.",
    "If the tool increases review burden or produces large untrusted diffs, a lower price does not make it a better deal.": "Nếu công cụ làm tăng gánh nặng review hoặc tạo diff lớn khó tin cậy, giá thấp hơn cũng không khiến nó thành lựa chọn tốt hơn.",
    "Windsurf is the main alternative to consider if you want another AI-first or agent-style editor workflow.": "Windsurf là lựa chọn thay thế chính nếu bạn muốn thử một workflow editor AI-first hoặc kiểu agent khác.",
    "Codeium is worth reviewing if your team wants a different coding assistant comparison point.": "Codeium đáng xem nếu team muốn có thêm một điểm so sánh trong nhóm coding assistant.",
    "For a broader view, start with the best AI coding tools guide.": "Để có góc nhìn rộng hơn, hãy bắt đầu với hướng dẫn các công cụ AI coding tốt nhất.",
    "The safest path is to test Copilot and Cursor on the same tasks: a bug fix, a refactor, a test-writing task, and a code explanation task.": "Cách an toàn nhất là test Copilot và Cursor trên cùng một nhóm task: sửa bug, refactor, viết test và giải thích code.",
    "Then compare not only speed, but also how much cleanup and review each output required.": "Sau đó không chỉ so tốc độ, mà còn so lượng cleanup và review cần làm với output của từng công cụ.",
    "My current AI coding workflow": "Workflow AI coding hiện tại của tôi",
    "High for active solo builders.": "Cao với solo builder dùng thường xuyên.",
    "High if agent workflow reduces handoffs.": "Cao nếu workflow agent giảm được số lần bàn giao thủ công.",
    "High for teams that want low disruption.": "Cao với team muốn ít xáo trộn workflow.",
    "High for expensive debugging sessions where correctness matters.": "Cao với các phiên debug tốn kém, nơi độ đúng quan trọng hơn tốc độ.",
    "Start with the option that matches your current workflow, then verify current pricing and terms on the official site.": "Hãy bắt đầu với lựa chọn khớp workflow hiện tại của bạn, sau đó xác minh giá và điều khoản mới nhất trên website chính thức.",
    "Every outbound CTA routes through local click tracking.": "Mọi CTA outbound đều đi qua tracking nội bộ.",
    "GitHub Copilot remains the obvious alternative if you want AI assistance without adopting an AI-first editor.": "GitHub Copilot vẫn là lựa chọn thay thế rõ ràng nếu bạn muốn AI hỗ trợ mà không phải chuyển sang editor AI-first.",
    "Codeium is another comparison point for teams considering coding assistant options.": "Codeium là một điểm so sánh khác cho team đang cân nhắc các coding assistant.",
    "For broader research, use the AI coding tools category page and the pricing guides.": "Để nghiên cứu rộng hơn, hãy dùng trang danh mục AI coding tools và các hướng dẫn giá.",
    "If neither Cursor nor Windsurf feels right, the problem may not be the tool.": "Nếu cả Cursor lẫn Windsurf đều chưa phù hợp, vấn đề có thể không nằm ở bản thân công cụ.",
    "Your team may need a clearer AI coding policy, better test coverage, smaller pull requests, or a narrower pilot before choosing a paid assistant.": "Team của bạn có thể cần chính sách AI coding rõ hơn, test coverage tốt hơn, pull request nhỏ hơn hoặc pilot hẹp hơn trước khi chọn một trợ lý trả phí.",
    "I tested Cursor vs Windsurf on a real project by giving both tools the same kind of task: understand an existing module, edit more than one file, explain a failing check, and keep the final change easy to review.": "Tôi test Cursor và Windsurf trên một dự án thật bằng cùng một kiểu task: hiểu một module có sẵn, chỉnh nhiều hơn một file, giải thích check đang fail và giữ thay đổi cuối cùng đủ dễ review.",
    "That is where the difference between controlled editor assistance and agent-style momentum becomes obvious.": "Đó là lúc khác biệt giữa hỗ trợ trong editor có kiểm soát và đà làm việc kiểu agent trở nên rõ hơn.",
    "My Copilot workflow is different from my Cursor workflow.": "Workflow Copilot của tôi khác với workflow Cursor.",
    "I treat Copilot like a fast pair of hands for autocomplete, small functions, and familiar patterns.": "Tôi xem Copilot như một đôi tay nhanh cho autocomplete, function nhỏ và các pattern quen thuộc.",
    "When the job becomes architecture, deployment, or cross-file debugging, I move the problem into a tool that can reason with more project context.": "Khi công việc chuyển sang kiến trúc, deploy hoặc debug nhiều file, tôi đưa vấn đề sang công cụ có khả năng suy luận với nhiều ngữ cảnh dự án hơn.",
    "The fastest workflow is usually a handoff chain.": "Workflow nhanh nhất thường là một chuỗi bàn giao giữa các công cụ.",
    "First I let an agent draft the rough shape when the project is still flexible.": "Đầu tiên tôi để agent dựng phần thô khi dự án còn linh hoạt.",
    "Then I switch to a controlled editor loop for targeted edits, naming cleanup, and small refactors.": "Sau đó tôi chuyển sang vòng lặp editor có kiểm soát để chỉnh đúng điểm, dọn naming và refactor nhỏ.",
    "When the build breaks, I stop generating new features and use a reasoning-heavy pass to read the error, inspect the touched files, and reduce the diff until the tests make sense again.": "Khi build lỗi, tôi dừng tạo feature mới và dùng một lượt suy luận kỹ để đọc lỗi, kiểm tra file đã chạm vào và thu nhỏ diff cho đến khi test hợp lý trở lại.",
    "Windsurf shines when I want speed at the beginning of a task, especially when the goal is to explore structure quickly.": "Windsurf mạnh khi tôi cần tốc độ ở đầu task, đặc biệt khi mục tiêu là khám phá cấu trúc nhanh.",
    "Cursor becomes stronger once the project already has a clean shape and the next job is to modify code without losing control.": "Cursor mạnh hơn khi dự án đã có cấu trúc tương đối sạch và việc tiếp theo là chỉnh code mà không mất kiểm soát.",
    "Copilot is useful in the background for completion, but I do not rely on it to understand the whole application.": "Copilot hữu ích ở nền cho việc hoàn thành code, nhưng tôi không dựa vào nó để hiểu toàn bộ ứng dụng.",
    "Codex-style debugging is where I want a tool to slow down, read the codebase, and fix the architecture instead of adding another layer of generated code.": "Debug kiểu Codex là lúc tôi muốn công cụ chậm lại, đọc codebase và sửa kiến trúc thay vì thêm một lớp code sinh tự động nữa.",
    "The cost tradeoff is also practical.": "Tradeoff chi phí cũng rất thực tế.",
    "I do not want to spend high-reasoning tool time on tiny autocomplete tasks.": "Tôi không muốn dùng thời gian của công cụ suy luận mạnh cho các task autocomplete nhỏ.",
    "I also do not want cheap autocomplete deciding a migration strategy.": "Tôi cũng không muốn một công cụ autocomplete rẻ quyết định chiến lược migration.",
    "The best setup uses each assistant at the point where it creates the least cleanup.": "Cách setup tốt nhất là dùng từng trợ lý ở đúng điểm mà nó tạo ra ít cleanup nhất.",
    "Cursor becomes extremely powerful when the project structure is already clean.": "Cursor trở nên rất mạnh khi cấu trúc dự án đã sạch.",
    "Windsurf is faster when you need a first draft.": "Windsurf nhanh hơn khi bạn cần bản nháp đầu tiên.",
    "Copilot is convenient for small edits.": "Copilot tiện cho các chỉnh sửa nhỏ.",
    "Codex-style reasoning is what I reach for when the build, tests, or deployment pipeline is actually broken.": "Suy luận kiểu Codex là thứ tôi dùng khi build, test hoặc pipeline deploy thật sự bị hỏng.",
    "Clear use case fit and useful research signals.": "Use case rõ và có tín hiệu nghiên cứu hữu ích.",
    "Policy and pricing should be verified on the official website.": "Chính sách và giá nên được xác minh trên website chính thức.",
    "Check official pricing for both tools before buying, writing affiliate content, or sending paid traffic.": "Hãy kiểm tra giá chính thức của cả hai công cụ trước khi mua, viết nội dung affiliate hoặc chạy traffic trả phí.",
    "The important details are not only monthly price.": "Chi tiết quan trọng không chỉ là giá tháng.",
    "Look at usage limits, model access, team seats, repository privacy, enterprise controls, and cancellation rules.": "Hãy xem giới hạn sử dụng, quyền truy cập model, seat team, quyền riêng tư repository, kiểm soát doanh nghiệp và điều khoản hủy.",
    "AI coding tools can look inexpensive for one person and become a different calculation when rolled out across a team.": "AI coding tools có thể trông rẻ với một người, nhưng bài toán sẽ khác khi triển khai cho cả team.",
    "If you are evaluating affiliate content, do not quote old prices as if they are permanent.": "Nếu bạn đang đánh giá nội dung affiliate, đừng trích giá cũ như thể nó luôn đúng.",
    "A safer page says pricing may change and directs the reader to verify current pricing on the official site through a tracked CTA.": "Cách an toàn hơn là nói rõ giá có thể thay đổi và dẫn người đọc kiểm tra giá hiện tại trên website chính thức qua CTA có tracking.",
    "Is Cursor better than Windsurf?": "Cursor có tốt hơn Windsurf không?",
    "Is Copilot better than Cursor for companies?": "Copilot có phù hợp hơn Cursor cho doanh nghiệp không?",
    "Is Cursor better for solo developers?": "Cursor có phù hợp hơn cho developer làm một mình không?",
    "Which tool has better context awareness?": "Công cụ nào hiểu ngữ cảnh tốt hơn?",
    "Should companies replace Copilot with Cursor?": "Doanh nghiệp có nên thay Copilot bằng Cursor không?",
    "What is the safest way to test both tools?": "Cách an toàn nhất để thử cả hai công cụ là gì?",
    "Who should use Framer?": "Ai nên dùng Framer?",
    "Who should use Webflow?": "Ai nên dùng Webflow?",
    "Framer vs Webflow: which tool should you choose?": "Framer vs Webflow: nên chọn công cụ nào?",
    "Who should use Cursor?": "Ai nên dùng Cursor?",
    "Who should use Windsurf?": "Ai nên dùng Windsurf?",
    "Cursor vs Windsurf: which tool should you choose?": "Cursor vs Windsurf: nên chọn công cụ nào?",
    "How should you compare pricing?": "Nên so sánh giá như thế nào?",
    "Does this page use affiliate links?": "Trang này có dùng liên kết affiliate không?",
    "Use this page as a research starting point, then verify pricing, terms, policy, and workflow fit on the official website before buying or promoting either tool.": "Hãy dùng trang này như điểm bắt đầu nghiên cứu, sau đó xác minh giá, điều khoản, chính sách và mức phù hợp workflow trên website chính thức trước khi mua hoặc quảng bá bất kỳ công cụ nào.",
    "Which is better for multi-file editing?": "Công cụ nào tốt hơn cho chỉnh sửa nhiều file?",
    "Which tool is easier to onboard?": "Công cụ nào dễ làm quen hơn?",
    "Should teams switch from Copilot to Cursor or Windsurf?": "Team có nên chuyển từ Copilot sang Cursor hoặc Windsurf không?",
    "How should I compare pricing?": "Nên so sánh giá như thế nào?",
    "Can either tool replace a senior developer?": "Hai công cụ này có thể thay senior developer không?",
    "Cursor is the safer first test if you want an AI-first editor with strong control.": "Cursor là lựa chọn thử đầu tiên an toàn hơn nếu bạn muốn editor AI-first nhưng vẫn cần kiểm soát tốt.",
    "Windsurf is worth testing if you want to evaluate a more agent-style coding workflow.": "Windsurf đáng thử nếu bạn muốn đánh giá workflow lập trình kiểu agent hơn.",
    "Both should be tested on the same repository task.": "Cả hai nên được test trên cùng một task trong cùng repository.",
    "Cursor is strong for guided multi-file work; Windsurf is interesting when the task feels more like a workflow agent problem.": "Cursor mạnh với công việc nhiều file có hướng dẫn rõ; Windsurf thú vị hơn khi task giống vấn đề workflow agent.",
    "Cursor may feel easier for developers already comfortable with AI editor workflows.": "Cursor có thể dễ làm quen hơn với developer đã quen workflow editor có AI.",
    "Windsurf can require more evaluation time if the team is new to agent-style coding.": "Windsurf có thể cần nhiều thời gian đánh giá hơn nếu team mới với cách code kiểu agent.",
    "Not immediately. Run a limited pilot, compare developer adoption, review quality, security requirements, and actual time saved.": "Không nên chuyển ngay. Hãy chạy pilot nhỏ, so mức developer chấp nhận, chất lượng review, yêu cầu bảo mật và thời gian thật sự tiết kiệm được.",
    "Use the official pricing pages and check seat cost, limits, model access, privacy controls, cancellation, and whether the needed features are included.": "Dùng trang giá chính thức và kiểm tra chi phí seat, giới hạn, quyền truy cập model, kiểm soát riêng tư, điều khoản hủy và tính năng cần thiết có được bao gồm không.",
    "No. These tools can speed up research and implementation, but architecture, testing, code review, and production responsibility still require human judgment.": "Không. Các công cụ này có thể tăng tốc nghiên cứu và triển khai, nhưng kiến trúc, kiểm thử, review code và trách nhiệm production vẫn cần phán đoán của con người.",
    "Cursor review": "Review Cursor",
    "Windsurf review": "Review Windsurf",
    "GitHub Copilot review": "Review GitHub Copilot",
    "Cursor pricing": "Giá Cursor",
    "AI coding tools category": "Danh mục công cụ AI coding",
    "Best AI Coding Tools": "Công cụ AI coding tốt nhất",
    "Best AI Coding Tools 2026": "Công cụ AI coding tốt nhất năm 2026",
    "Best AI SEO Tools": "Công cụ AI SEO tốt nhất",
    "Best AI Automation Tools": "Công cụ tự động hóa AI tốt nhất",
    "Best AI Presentation Tools": "Công cụ trình bày AI tốt nhất",
    "AI Coding Tools": "Công cụ AI coding",
    "AI Automation Tools": "Công cụ tự động hóa AI",
    "Best AI Coding Công cụs 2026: Cursor, Windsurf, Copilot, and Practical Buying Advice": "Công cụ AI coding tốt nhất 2026: Cursor, Windsurf, Copilot và lời khuyên mua hàng thực tế",
    "Best AI Coding Công cụs": "Công cụ AI coding tốt nhất",
    "Best AI Automation Công cụs": "Công cụ tự động hóa AI tốt nhất",
    "Best AI Presentation Công cụs": "Công cụ trình bày AI tốt nhất",
    "Best AI SEO Công cụs": "Công cụ AI SEO tốt nhất",
    "AI Automation Công cụs": "Công cụ tự động hóa AI",
    "Plans, Trial Notes, and Buying Risks": "gói dịch vụ, ghi chú dùng thử và rủi ro khi mua",
    "Which AI coding assistants should you choose?": "Nên chọn trợ lý lập trình AI nào?",
    "Which AI coding tools should you choose?": "Nên chọn công cụ lập trình AI nào?",
    "Which AI coding editors should you choose?": "Nên chọn editor AI coding nào?",
    "Which Tool Should You Choose in 2026?": "Nên chọn công cụ nào trong năm 2026?",
    "Which email marketing platforms should you choose?": "Nên chọn nền tảng email marketing nào?",
    "Which AI design and ad creative tools should you choose?": "Nên chọn công cụ thiết kế và tạo quảng cáo AI nào?",
    "Which AI writing assistants should you choose?": "Nên chọn trợ lý viết AI nào?",
}


def localize_html(text: str) -> str:
    """Normalize common generated UI labels to Vietnamese.

    This is intentionally conservative: it targets repeated template copy and
    known mojibake strings without changing brand names or URLs.
    """
    for source, target in MOJIBAKE_REPLACEMENTS.items():
        text = text.replace(source, target)
    text = text.replace('<html lang="en">', '<html lang="vi">')
    text = text.replace("<html lang='en'>", "<html lang='vi'>")
    for source, target in PHRASE_REPLACEMENTS.items():
        text = text.replace(source, target)
    for source, target in PAGE_TEXT_REPLACEMENTS.items():
        text = text.replace(source, target)
    text = re.sub(
        r"Is ([A-Za-z0-9 .+&-]+) better than ([A-Za-z0-9 .+&-]+)\?",
        lambda match: f"{match.group(1).strip()} có tốt hơn {match.group(2).strip()} không?",
        text,
    )
    text = re.sub(
        r"How should teams compare ([A-Za-z0-9 .+&-]+) and ([A-Za-z0-9 .+&-]+) pricing\?",
        lambda match: f"Team nên so sánh giá {match.group(1).strip()} và {match.group(2).strip()} như thế nào?",
        text,
    )
    text = text.replace("Which tool is easier for beginners?", "Công cụ nào dễ hơn cho người mới?")
    text = text.replace("What should I verify before buying either tool?", "Tôi nên xác minh gì trước khi mua một trong hai công cụ?")
    text = text.replace("Can I promote these tools as an affiliate?", "Tôi có thể quảng bá các công cụ này theo affiliate không?")
    text = text.replace("Should I read individual reviews before choosing?", "Tôi có nên đọc từng bài review trước khi chọn không?")
    # Replace longer UI strings before short words to avoid partial conflicts.
    for source, target in sorted(UI_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)



    extra_replacements = {
        "Best for": "Ph? h?p v?i",
        "Not best for": "Kh?ng ph? h?p n?u",
        "When to use it": "Khi n?o n?n d?ng?",
        "When not to use it": "Khi n?o kh?ng n?n d?ng?",
        "Workflow fit": "Workflow ph? h?p",
        "Best audience": "??i t??ng ph? h?p nh?t",
        "What problem does this tool solve?": "C?ng c? n?y gi?i quy?t vi?c g??",
        "Who should consider it?": "Ai n?n c?n nh?c?",
        "Notable features": "T?nh n?ng ??ng ch? ?",
        "Standout strengths": "?i?m m?nh n?i b?t",
        "Friction points": "?i?m c?n l?u ?",
        "Cons / limitations": "H?n ch?",
        "Pros and cons table": "B?ng ?u ?i?m v? h?n ch?",
        "Score explanation": "Gi?i th?ch ?i?m s?",
        "Pricing note": "Ghi ch? gi?",
        "Pricing summary": "T?m t?t gi?",
        "Verify current pricing on the official website.": "H?y x?c minh gi? hi?n t?i tr?n website ch?nh th?c.",
        "Pricing, trials, plan limits, and cancellation terms can change over time.": "Gi?, b?n d?ng th?, gi?i h?n g?i v? ?i?u kho?n h?y c? th? thay ??i theo th?i gian.",
        "Verify on the official website": "X?c minh tr?n website ch?nh th?c",
        "This review evaluates": "B?i review n?y ??nh gi?",
        "from a practical research angle": "theo h??ng nghi?n c?u th?c t?",
        "which strengths matter": "?i?m m?nh n?o quan tr?ng",
        "which limitations need checking": "h?n ch? n?o c?n ki?m tra",
        "and whether it deserves a place on your shortlist": "v? li?u c? ??ng ??a v?o shortlist hay kh?ng",
        "The responsible approach is to treat this as a first-pass filter": "C?ch h?p l? l? xem ??y nh? m?t b??c l?c ban ??u",
        "then verify pricing, integrations, usage rights, and official terms before buying or promoting it": "sau ?? x?c minh gi?, t?ch h?p, quy?n s? d?ng v? ?i?u kho?n ch?nh th?c tr??c khi mua ho?c qu?ng b?",
        "The usability signal looks relatively strong.": "T?n hi?u usability t??ng ??i t?t.",
        "Pricing still needs to be checked on the official website before buying.": "Gi? v?n c?n ki?m tra tr?n website ch?nh th?c tr??c khi mua.",
        "This is research content, not a promise of business results or advertising performance.": "??y l? n?i dung nghi?n c?u, kh?ng ph?i cam k?t k?t qu? kinh doanh ho?c hi?u qu? qu?ng c?o.",
    }
    for source, target in sorted(extra_replacements.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)

    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Review: Features, Pros, Cons, Pricing Notes",
        lambda m: f"{m.group(1).strip()} Đánh giá: tính năng, ưu điểm, hạn chế và ghi chú giá",
        text,
    )
    text = re.sub(
        r">([A-Za-z0-9 .+&-]+) Đánh giá<",
        lambda m: f">Đánh giá {m.group(1).strip()}<",
        text,
    )
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Đánh giá: tính năng",
        lambda m: f"Đánh giá {m.group(1).strip()}: tính năng",
        text,
    )
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Pricing Guide: Plans, Trial Notes, and Buying Risks",
        lambda m: f"Hướng dẫn giá {m.group(1).strip()}: gói dịch vụ, dùng thử và rủi ro khi mua",
        text,
    )
    # Keep JSON-LD schema type values machine-readable after visible UI translation.
    text = text.replace('"@type": "Câu hỏi thường gặpPage"', '"@type": "FAQPage"')
    text = text.replace('"@type":"Câu hỏi thường gặpPage"', '"@type":"FAQPage"')
    text = text.replace('"@type": "Đánh giá"', '"@type": "Review"')
    text = text.replace('"@type":"Đánh giá"', '"@type":"Review"')
    # Preserve the public site identity. Generic UI localization of "Review"
    # should not rewrite the brand name into a half-translated phrase.
    text = text.replace("MS Smile AI Đánh giá Hub", "MS Smile AI Review Hub")
    text = text.replace("MS Smile AI Review Trung tâm", "MS Smile AI Review Hub")
    text = text.replace("Trung tâm đánh giá MS Smile AI", "MS Smile AI Review Hub")
    text = text.replace("Công cụ AI Đánh giá Hub", "MS Smile AI Review Hub")
    text = text.replace("Công cụ AI Review Hub", "MS Smile AI Review Hub")
    # Final cleanup for mixed-language fragments generated by automatic
    # internal-link titles, metadata, and schema text. Keep brand/product names
    # unchanged, but normalize repeated editorial phrases into Vietnamese.
    cleanup_pairs = {
        "pricing note": "ghi chú giá",
        "Pricing note": "Ghi chú giá",
        "Pricing Notes": "Ghi chú giá",
        "affiliate disclosure": "tiết lộ liên kết",
        "Affiliate disclosure": "Tiết lộ liên kết",
        "pricing, integrations": "giá, tích hợp",
        "pricing, tích hợp": "giá, tích hợp",
        "integrations": "tích hợp",
        "Integrations": "Tích hợp",
        "Ghi chú pricing": "Ghi chú giá",
        "Tóm tắt pricing": "Tóm tắt giá",
        "Giá Checks": "kiểm tra giá",
        "Workflow Fit": "mức phù hợp workflow",
        "Research-Style Đánh giá": "review theo hướng nghiên cứu",
        "Research-style editorial review focused on workflow fit, pricing verification, alternatives, and affiliate disclosure.": "Review biên tập theo hướng nghiên cứu, tập trung vào mức phù hợp workflow, kiểm tra giá, lựa chọn thay thế và tiết lộ liên kết.",
        "Use this page as a research starting point. Verify pricing, product limits, refund or cancellation terms, integrations, and official vendor policies before buying or promoting the tool.": "Hãy dùng trang này như điểm bắt đầu nghiên cứu. Cần xác minh giá, giới hạn sản phẩm, điều khoản hoàn tiền hoặc hủy gói, tích hợp và chính sách chính thức của vendor trước khi mua hoặc quảng bá công cụ.",
        "Use this page as editorial research. Verify pricing, limits, affiliate chính sách, and official terms before buying or promoting any tool.": "Hãy xem trang này như tài liệu nghiên cứu biên tập. Cần xác minh giá, giới hạn, chính sách affiliate và điều khoản chính thức trước khi mua hoặc quảng bá bất kỳ công cụ nào.",
        "Kiểm tra giá chính thức for both tools before making a decision.": "Hãy kiểm tra giá chính thức của cả hai công cụ trước khi ra quyết định.",
        "Compare category leaders": "So sánh các công cụ dẫn đầu danh mục",
        "Check direct competitors": "Kiểm tra đối thủ trực tiếp",
        "Đánh giá budget-friendly options": "Đánh giá các lựa chọn hợp ngân sách",
        "Cursor pros": "Ưu điểm của Cursor",
        "Cursor cons": "Hạn chế của Cursor",
        "Pros of Cursor": "Ưu điểm của Cursor",
        "Limitations of Cursor": "Hạn chế của Cursor",
        "Cons of Cursor": "Hạn chế của Cursor",
        "Windsurf pros": "Ưu điểm của Windsurf",
        "Windsurf cons": "Hạn chế của Windsurf",
        "Pros of Windsurf": "Ưu điểm của Windsurf",
        "Limitations of Windsurf": "Hạn chế của Windsurf",
        "Cons of Windsurf": "Hạn chế của Windsurf",
        "GitHub Copilot pros": "Ưu điểm của GitHub Copilot",
        "GitHub Copilot cons": "Hạn chế của GitHub Copilot",
        "Pros of GitHub Copilot": "Ưu điểm của GitHub Copilot",
        "Limitations of GitHub Copilot": "Hạn chế của GitHub Copilot",
        "Cons of GitHub Copilot": "Hạn chế của GitHub Copilot",
        "Strong fit for developers who want AI inside the editor rather than in a separate chat tab.": "Phù hợp với developer muốn AI nằm ngay trong editor thay vì ở một tab chat riêng.",
        "Good option for codebase explanation, targeted edits, and iterative refactors.": "Hữu ích cho việc giải thích codebase, chỉnh sửa có mục tiêu và refactor lặp lại.",
        "Feels practical for solo builders who need speed but still want control.": "Thực tế với solo builder cần tốc độ nhưng vẫn muốn kiểm soát.",
        "Moving editors can be a real adoption cost for teams.": "Chuyển editor có thể là chi phí áp dụng thật sự với team.",
        "The output still needs tests and careful code review.": "Output vẫn cần test và review code cẩn thận.",
        "Giá and usage limits should be checked before scaling to a team.": "Cần kiểm tra giá và giới hạn sử dụng trước khi mở rộng cho team.",
        "Interesting for agent-style coding where the assistant helps with a sequence of steps.": "Đáng chú ý với workflow code kiểu agent, nơi trợ lý hỗ trợ theo chuỗi nhiều bước.",
        "Useful to test if Cursor feels too manual for larger workflow tasks.": "Đáng test nếu Cursor còn quá thủ công với các task workflow lớn.",
        "A good benchmark when evaluating the next generation of AI coding editors.": "Là điểm benchmark tốt khi đánh giá thế hệ editor AI coding mới.",
        "Teams may need more time to judge maturity, chính sách, and workflow fit.": "Team có thể cần thêm thời gian để đánh giá độ chín, chính sách và mức phù hợp workflow.",
        "Developers who want a conservative IDE setup may resist another editor change.": "Developer muốn giữ IDE bảo thủ có thể không muốn đổi thêm editor.",
        "As with any AI coding tool, generated changes can be plausible and still wrong.": "Như mọi công cụ AI coding, thay đổi được sinh ra có thể trông hợp lý nhưng vẫn sai.",
        "Best AI coding tools 2026": "Công cụ AI coding tốt nhất 2026",
        "and Practical Buying Advice": "và lời khuyên mua hàng thực tế",
        "to Research Before You Buy": "cần nghiên cứu trước khi mua",
        "Đánh giá for AI Coding Buyers: mức phù hợp workflow, kiểm tra giá, and Lựa chọn thay thế": "review cho người mua công cụ AI coding: mức phù hợp workflow, kiểm tra giá và lựa chọn thay thế",
        "Đánh giá for AI Coding Buyers: mức phù hợp workflow, kiểm tra giá, và Lựa chọn thay thế": "review cho người mua công cụ AI coding: mức phù hợp workflow, kiểm tra giá và lựa chọn thay thế",
        "Đánh giá: Tính năng, Ưu điểm, Hạn chế, Ghi chú giá": "review: tính năng, ưu điểm, hạn chế và ghi chú giá",
        "Best AI Coding Lựa chọn thay thế for 2026": "Lựa chọn thay thế AI coding tốt nhất năm 2026",
        "Best AI Design Lựa chọn thay thế for 2026": "Lựa chọn thay thế AI design tốt nhất năm 2026",
        "Best AI Meeting Lựa chọn thay thế for 2026": "Lựa chọn thay thế AI meeting tốt nhất năm 2026",
        "AI Coding Software Đánh giá: review theo hướng nghiên cứu for 2026": "Review phần mềm AI coding theo hướng nghiên cứu năm 2026",
    }
    for source, target in cleanup_pairs.items():
        text = text.replace(source, target)
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Đánh giá for AI Coding Buyers: mức phù hợp workflow, kiểm tra giá, (?:and|và) Lựa chọn thay thế",
        lambda m: f"Review {m.group(1).strip()} cho người mua công cụ AI coding: mức phù hợp workflow, kiểm tra giá và lựa chọn thay thế",
        text,
    )
    text = re.sub(
        r"([A-Za-z0-9 .+&-]+) Đánh giá: Tính năng, Ưu điểm, Hạn chế, Ghi chú giá",
        lambda m: f"Review {m.group(1).strip()}: tính năng, ưu điểm, hạn chế và ghi chú giá",
        text,
    )
    # Some visible-label replacements can accidentally touch JSON-LD property
    # names. Restore schema keys so structured data remains valid.
    text = text.replace('"itemĐánh giáed"', '"itemReviewed"')
    text = text.replace('"itemreviewed"', '"itemReviewed"')
    text = text.replace('"reviewRating"', '"reviewRating"')
    # Protect product names and pros/cons headings from accidental literal
    # translation. This also fixes older generated Vietnamese pages where
    # translation reduced a card title to only "con trỏ".
    text = re.sub(r"<h([1-6])>\s*con trỏ\s*</h\1>", r"<h\1>Hạn chế của Cursor</h\1>", text, flags=re.IGNORECASE)
    text = re.sub(r"<h([1-6])>\s*lướt ván buồm\s*</h\1>", r"<h\1>Hạn chế của Windsurf</h\1>", text, flags=re.IGNORECASE)
    text = text.replace("Ưu điểm của con trỏ", "Ưu điểm của Cursor")
    text = text.replace("Hạn chế của con trỏ", "Hạn chế của Cursor")
    text = text.replace("Nhược điểm của con trỏ", "Hạn chế của Cursor")
    text = text.replace("Ưu điểm của lướt ván buồm", "Ưu điểm của Windsurf")
    text = text.replace("Hạn chế của lướt ván buồm", "Hạn chế của Windsurf")
    text = text.replace("Nhược điểm của lướt ván buồm", "Hạn chế của Windsurf")
    text = text.replace("Ưu điểm of Cursor", "Ưu điểm của Cursor")
    text = text.replace("Ưu điểm of Windsurf", "Ưu điểm của Windsurf")
    text = text.replace("Ưu điểm of GitHub Copilot", "Ưu điểm của GitHub Copilot")
    text = text.replace("Hạn chế of Cursor", "Hạn chế của Cursor")
    text = text.replace("Hạn chế of Windsurf", "Hạn chế của Windsurf")
    text = text.replace("Hạn chế of GitHub Copilot", "Hạn chế của GitHub Copilot")
    return text
